// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package syslog

import "github.com/browningluke/opnsense-go/pkg/api"

const syslogReconfigureEndpoint = "/syslog/service/reconfigure"

// Controller for syslog
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
