// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package syslog

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var DestinationOpts = api.ReqOpts{
	AddEndpoint:         "/syslog/settings/addDestination",
	GetEndpoint:         "/syslog/settings/getDestination",
	UpdateEndpoint:      "/syslog/settings/setDestination",
	DeleteEndpoint:      "/syslog/settings/delDestination",
	ReconfigureEndpoint: syslogReconfigureEndpoint,
	Monad:               "destination",
}

// Data structs

type Destination struct {
	Enabled     string              `json:"enabled"`
	Transport   api.SelectedMap     `json:"transport"`
	Level       api.SelectedMap     `json:"level"`
	Facility    api.SelectedMapList `json:"facility"`
	Program     api.SelectedMapList `json:"program"`
	Hostname    string              `json:"hostname"`
	Certificate api.SelectedMap     `json:"certificate"`
	Port        string              `json:"port"`
	Rfc5424     string              `json:"rfc5424"`
	Description string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddDestination(ctx context.Context, resource *Destination) (string, error) {
	return api.Add(c.Client(), ctx, DestinationOpts, resource)
}

func (c *Controller) GetDestination(ctx context.Context, id string) (*Destination, error) {
	return api.Get(c.Client(), ctx, DestinationOpts, &Destination{}, id)
}

func (c *Controller) UpdateDestination(ctx context.Context, id string, resource *Destination) error {
	return api.Update(c.Client(), ctx, DestinationOpts, resource, id)
}

func (c *Controller) DeleteDestination(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, DestinationOpts, id)
}
