// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ipsec

import "github.com/browningluke/opnsense-go/pkg/api"

const ipsecReconfigureEndpoint = "/ipsec/service/reconfigure"

// Controller for ipsec
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
