// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ipsec

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var IPsecAuthLocalOpts = api.ReqOpts{
	AddEndpoint:         "/ipsec/connections/add_local",
	GetEndpoint:         "/ipsec/connections/get_local",
	UpdateEndpoint:      "/ipsec/connections/set_local",
	DeleteEndpoint:      "/ipsec/connections/del_local",
	ReconfigureEndpoint: ipsecReconfigureEndpoint,
	Monad:               "local",
}

// Data structs

type IPsecAuthLocal struct {
	Enabled        string              `json:"enabled"`
	Connection     api.SelectedMap     `json:"connection"`
	Round          string              `json:"round"`
	Authentication api.SelectedMap     `json:"auth"`
	Id             string              `json:"id"`
	EAPId          string              `json:"eap_id"`
	Certificates   api.SelectedMapList `json:"certs"`
	PublicKeys     api.SelectedMapList `json:"public_keys"`
	Description    string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddIPsecAuthLocal(ctx context.Context, resource *IPsecAuthLocal) (string, error) {
	return api.Add(c.Client(), ctx, IPsecAuthLocalOpts, resource)
}

func (c *Controller) GetIPsecAuthLocal(ctx context.Context, id string) (*IPsecAuthLocal, error) {
	return api.Get(c.Client(), ctx, IPsecAuthLocalOpts, &IPsecAuthLocal{}, id)
}

func (c *Controller) UpdateIPsecAuthLocal(ctx context.Context, id string, resource *IPsecAuthLocal) error {
	return api.Update(c.Client(), ctx, IPsecAuthLocalOpts, resource, id)
}

func (c *Controller) DeleteIPsecAuthLocal(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, IPsecAuthLocalOpts, id)
}
