// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package monit

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var AlertOpts = api.ReqOpts{
	AddEndpoint:         "/monit/settings/addAlert",
	GetEndpoint:         "/monit/settings/getAlert",
	UpdateEndpoint:      "/monit/settings/setAlert",
	DeleteEndpoint:      "/monit/settings/delAlert",
	ReconfigureEndpoint: monitReconfigureEndpoint,
	Monad:               "alert",
}

// Data structs

type Alert struct {
	Enabled     string              `json:"enabled"`
	Recipient   string              `json:"recipient"`
	Noton       string              `json:"noton"`
	Events      api.SelectedMapList `json:"events"`
	Format      string              `json:"format"`
	Reminder    string              `json:"reminder"`
	Description string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddAlert(ctx context.Context, resource *Alert) (string, error) {
	return api.Add(c.Client(), ctx, AlertOpts, resource)
}

func (c *Controller) GetAlert(ctx context.Context, id string) (*Alert, error) {
	return api.Get(c.Client(), ctx, AlertOpts, &Alert{}, id)
}

func (c *Controller) UpdateAlert(ctx context.Context, id string, resource *Alert) error {
	return api.Update(c.Client(), ctx, AlertOpts, resource, id)
}

func (c *Controller) DeleteAlert(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AlertOpts, id)
}
