// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package monit

import "github.com/browningluke/opnsense-go/pkg/api"

const monitReconfigureEndpoint = "/monit/service/reconfigure"

// Controller for monit
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
