// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package monit

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var ServiceOpts = api.ReqOpts{
	AddEndpoint:         "/monit/settings/addService",
	GetEndpoint:         "/monit/settings/getService",
	UpdateEndpoint:      "/monit/settings/setService",
	DeleteEndpoint:      "/monit/settings/delService",
	ReconfigureEndpoint: monitReconfigureEndpoint,
	Monad:               "service",
}

// Data structs

type Service struct {
	Enabled      string              `json:"enabled"`
	Name         string              `json:"name"`
	Description  string              `json:"description"`
	Type         api.SelectedMap     `json:"type"`
	Pidfile      string              `json:"pidfile"`
	Match        string              `json:"match"`
	Path         string              `json:"path"`
	Timeout      string              `json:"timeout"`
	Starttimeout string              `json:"starttimeout"`
	Address      string              `json:"address"`
	Interface    api.SelectedMap     `json:"interface"`
	Start        string              `json:"start"`
	Stop         string              `json:"stop"`
	Tests        api.SelectedMapList `json:"tests"`
	Depends      api.SelectedMapList `json:"depends"`
	Polltime     string              `json:"polltime"`
}

// CRUD operations

func (c *Controller) AddService(ctx context.Context, resource *Service) (string, error) {
	return api.Add(c.Client(), ctx, ServiceOpts, resource)
}

func (c *Controller) GetService(ctx context.Context, id string) (*Service, error) {
	return api.Get(c.Client(), ctx, ServiceOpts, &Service{}, id)
}

func (c *Controller) UpdateService(ctx context.Context, id string, resource *Service) error {
	return api.Update(c.Client(), ctx, ServiceOpts, resource, id)
}

func (c *Controller) DeleteService(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ServiceOpts, id)
}
