// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package monit

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type ActionResult struct {
	Status string `json:"status"`
}

type Result struct {
	Result string `json:"result"`
}

type Settings struct {
	Enabled                   string              `json:"enabled"`
	Interval                  string              `json:"interval"`
	Startdelay                string              `json:"startdelay"`
	Mailserver                api.SelectedMapList `json:"mailserver"`
	Port                      string              `json:"port"`
	Username                  string              `json:"username"`
	Password                  string              `json:"password"`
	Ssl                       string              `json:"ssl"`
	SslVersion                api.SelectedMap     `json:"sslversion"`
	SslVerify                 string              `json:"sslverify"`
	Logfile                   string              `json:"logfile"`
	Statefile                 string              `json:"statefile"`
	EventqueuePath            string              `json:"eventqueuePath"`
	EventqueueSlots           string              `json:"eventqueueSlots"`
	HttpdEnabled              string              `json:"httpdEnabled"`
	HttpdUsername             string              `json:"httpdUsername"`
	HttpdPassword             string              `json:"httpdPassword"`
	HttpdPort                 string              `json:"httpdPort"`
	HttpdAllow                api.SelectedMapList `json:"httpdAllow"`
	MmonitUrl                 string              `json:"mmonitUrl"`
	MmonitTimeout             string              `json:"mmonitTimeout"`
	MmonitRegisterCredentials string              `json:"mmonitRegisterCredentials"`
}

type SettingsGeneral struct {
	General Settings `json:"general"`
}

type SettingsMonad struct {
	Monit SettingsGeneral `json:"monit"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsMonad, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/monit/settings/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsMonad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, monit *SettingsGeneral) (*Result, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["monit"] = monit

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/monit/settings/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}

// SettingsReconfigure executes the Reconfigure RPC call of the Settings controller
func (c *Controller) SettingsReconfigure(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/monit/service/reconfigure",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reconfigure call failed: %w", err)
	}
	return result, nil
}
