// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package monit

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var TestOpts = api.ReqOpts{
	AddEndpoint:         "/monit/settings/addTest",
	GetEndpoint:         "/monit/settings/getTest",
	UpdateEndpoint:      "/monit/settings/setTest",
	DeleteEndpoint:      "/monit/settings/delTest",
	ReconfigureEndpoint: monitReconfigureEndpoint,
	Monad:               "test",
}

// Data structs

type Test struct {
	Name      string          `json:"name"`
	Type      api.SelectedMap `json:"type"`
	Condition string          `json:"condition"`
	Action    api.SelectedMap `json:"action"`
	Path      string          `json:"path"`
}

// CRUD operations

func (c *Controller) AddTest(ctx context.Context, resource *Test) (string, error) {
	return api.Add(c.Client(), ctx, TestOpts, resource)
}

func (c *Controller) GetTest(ctx context.Context, id string) (*Test, error) {
	return api.Get(c.Client(), ctx, TestOpts, &Test{}, id)
}

func (c *Controller) UpdateTest(ctx context.Context, id string, resource *Test) error {
	return api.Update(c.Client(), ctx, TestOpts, resource, id)
}

func (c *Controller) DeleteTest(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, TestOpts, id)
}
