// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package openvpn

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var ClientOverwriteOpts = api.ReqOpts{
	AddEndpoint:         "/openvpn/client_overwrites/add",
	GetEndpoint:         "/openvpn/client_overwrites/get",
	UpdateEndpoint:      "/openvpn/client_overwrites/set",
	DeleteEndpoint:      "/openvpn/client_overwrites/del",
	ReconfigureEndpoint: openvpnReconfigureEndpoint,
	Monad:               "cso",
}

// Data structs

type ClientOverwrite struct {
	Enabled         string              `json:"enabled"`
	Servers         api.SelectedMapList `json:"servers"`
	CommonName      string              `json:"common_name"`
	Block           string              `json:"block"`
	PushReset       string              `json:"push_reset"`
	TunnelNetwork   string              `json:"tunnel_network"`
	TunnelNetworkV6 string              `json:"tunnel_networkv6"`
	LocalNetworks   api.SelectedMapList `json:"local_networks"`
	RemoteNetworks  api.SelectedMapList `json:"remote_networks"`
	RouteGateway    string              `json:"route_gateway"`
	RedirectGateway api.SelectedMapList `json:"redirect_gateway"`
	RegisterDNS     string              `json:"register_dns"`
	DNSDomain       api.SelectedMapList `json:"dns_domain"`
	DNSDomainSearch api.SelectedMapList `json:"dns_domain_search"`
	DNSServers      api.SelectedMapList `json:"dns_servers"`
	NTPServers      api.SelectedMapList `json:"ntp_servers"`
	WINSServers     api.SelectedMapList `json:"wins_servers"`
	Description     string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddClientOverwrite(ctx context.Context, resource *ClientOverwrite) (string, error) {
	return api.Add(c.Client(), ctx, ClientOverwriteOpts, resource)
}

func (c *Controller) GetClientOverwrite(ctx context.Context, id string) (*ClientOverwrite, error) {
	return api.Get(c.Client(), ctx, ClientOverwriteOpts, &ClientOverwrite{}, id)
}

func (c *Controller) UpdateClientOverwrite(ctx context.Context, id string, resource *ClientOverwrite) error {
	return api.Update(c.Client(), ctx, ClientOverwriteOpts, resource, id)
}

func (c *Controller) DeleteClientOverwrite(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ClientOverwriteOpts, id)
}
