// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package openvpn

import "github.com/browningluke/opnsense-go/pkg/api"

const openvpnReconfigureEndpoint = "/openvpn/service/reconfigure"

// Controller for openvpn
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
