// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package openvpn

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var InstanceOpts = api.ReqOpts{
	AddEndpoint:         "/openvpn/instances/add",
	GetEndpoint:         "/openvpn/instances/get",
	UpdateEndpoint:      "/openvpn/instances/set",
	DeleteEndpoint:      "/openvpn/instances/del",
	ReconfigureEndpoint: openvpnReconfigureEndpoint,
	Monad:               "instance",
}

// Data structs

type Instance struct {
	Enabled              string              `json:"enabled"`
	Role                 api.SelectedMap     `json:"role"`
	VPNID                string              `json:"vpnid,omitempty"`
	Description          string              `json:"description"`
	DevType              api.SelectedMap     `json:"dev_type"`
	Protocol             api.SelectedMap     `json:"proto"`
	Port                 string              `json:"port"`
	PortShare            string              `json:"port-share"`
	Local                string              `json:"local"`
	Remote               api.SelectedMapList `json:"remote"`
	Topology             api.SelectedMap     `json:"topology"`
	Server               string              `json:"server"`
	ServerIPv6           string              `json:"server_ipv6"`
	NoPool               string              `json:"nopool"`
	BridgeGateway        string              `json:"bridge_gateway"`
	BridgePool           string              `json:"bridge_pool"`
	Route                api.SelectedMapList `json:"route"`
	PushRoute            api.SelectedMapList `json:"push_route"`
	PushExcludedRoutes   api.SelectedMapList `json:"push_excluded_routes"`
	Certificate          api.SelectedMap     `json:"cert"`
	CRL                  api.SelectedMap     `json:"crl"`
	CertificateAuthority api.SelectedMap     `json:"ca"`
	CertDepth            api.SelectedMap     `json:"cert_depth"`
	RemoteCertTLS        string              `json:"remote_cert_tls"`
	VerifyClientCert     api.SelectedMap     `json:"verify_client_cert"`
	UseOCSP              string              `json:"use_ocsp"`
	AuthDigest           api.SelectedMap     `json:"auth"`
	DataCiphers          api.SelectedMapList `json:"data-ciphers"`
	DataCiphersFallback  api.SelectedMap     `json:"data-ciphers-fallback"`
	TLSKey               api.SelectedMap     `json:"tls_key"`
	AuthMode             api.SelectedMapList `json:"authmode"`
	LocalGroup           api.SelectedMap     `json:"local_group"`
	VariousFlags         api.SelectedMapList `json:"various_flags"`
	VariousPushFlags     api.SelectedMapList `json:"various_push_flags"`
	PushInactive         string              `json:"push_inactive"`
	UsernameAsCommonName string              `json:"username_as_common_name"`
	StrictUserCN         api.SelectedMap     `json:"strictusercn"`
	Username             string              `json:"username"`
	Password             string              `json:"password"`
	MaxClients           string              `json:"maxclients"`
	KeepaliveInterval    string              `json:"keepalive_interval"`
	KeepaliveTimeout     string              `json:"keepalive_timeout"`
	RenegSec             string              `json:"reneg-sec"`
	AuthGenToken         string              `json:"auth-gen-token"`
	AuthGenTokenRenewal  string              `json:"auth-gen-token-renewal"`
	AuthGenTokenSecret   string              `json:"auth-gen-token-secret"`
	ProvisionExclusive   string              `json:"provision_exclusive"`
	RedirectGateway      api.SelectedMapList `json:"redirect_gateway"`
	RouteMetric          string              `json:"route_metric"`
	RegisterDNS          string              `json:"register_dns"`
	DNSDomain            api.SelectedMapList `json:"dns_domain"`
	DNSDomainSearch      api.SelectedMapList `json:"dns_domain_search"`
	DNSServers           api.SelectedMapList `json:"dns_servers"`
	NTPServers           api.SelectedMapList `json:"ntp_servers"`
	TunMTU               string              `json:"tun_mtu"`
	Fragment             string              `json:"fragment"`
	MSSFix               string              `json:"mssfix"`
	CARPDependOn         api.SelectedMap     `json:"carp_depend_on"`
	CompressMigrate      string              `json:"compress_migrate"`
	IfConfigPoolPersist  string              `json:"ifconfig-pool-persist"`
	HTTPProxy            string              `json:"http-proxy"`
	VerifyX509Name       string              `json:"verify-x509-name"`
}

// CRUD operations

func (c *Controller) AddInstance(ctx context.Context, resource *Instance) (string, error) {
	return api.Add(c.Client(), ctx, InstanceOpts, resource)
}

func (c *Controller) GetInstance(ctx context.Context, id string) (*Instance, error) {
	return api.Get(c.Client(), ctx, InstanceOpts, &Instance{}, id)
}

func (c *Controller) UpdateInstance(ctx context.Context, id string, resource *Instance) error {
	return api.Update(c.Client(), ctx, InstanceOpts, resource, id)
}

func (c *Controller) DeleteInstance(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, InstanceOpts, id)
}
