// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package openvpn

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type ActionResult struct {
	Result string `json:"result"`
}

type GenKeyResult struct {
	Result string `json:"result"`
	Key    string `json:"key"`
}

type Result struct {
	Result string `json:"result"`
}

// ServiceReconfigure executes the Reconfigure RPC call of the Service controller
func (c *Controller) ServiceReconfigure(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/openvpn/service/reconfigure",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reconfigure call failed: %w", err)
	}
	return result, nil
}

// ServiceStartService executes the StartService RPC call of the Service controller
func (c *Controller) ServiceStartService(ctx context.Context, id *string) (*Result, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	if id != nil {
		callParams = append(callParams, *id)
	}

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/openvpn/service/start_service",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("StartService call failed: %w", err)
	}
	return result, nil
}

// ServiceStopService executes the StopService RPC call of the Service controller
func (c *Controller) ServiceStopService(ctx context.Context, id *string) (*Result, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	if id != nil {
		callParams = append(callParams, *id)
	}

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/openvpn/service/stop_service",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("StopService call failed: %w", err)
	}
	return result, nil
}

// ServiceRestartService executes the RestartService RPC call of the Service controller
func (c *Controller) ServiceRestartService(ctx context.Context, id *string) (*Result, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	if id != nil {
		callParams = append(callParams, *id)
	}

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/openvpn/service/restart_service",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("RestartService call failed: %w", err)
	}
	return result, nil
}

// ServiceGenKey executes the GenKey RPC call of the Service controller
func (c *Controller) ServiceGenKey(ctx context.Context, keyType *string) (*GenKeyResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	if keyType != nil {
		queryParams["type"] = *keyType
	}

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/openvpn/instances/gen_key",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GenKeyResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GenKey call failed: %w", err)
	}
	return result, nil
}
