// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package openvpn

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var StaticKeyOpts = api.ReqOpts{
	AddEndpoint:         "/openvpn/instances/add_static_key",
	GetEndpoint:         "/openvpn/instances/get_static_key",
	UpdateEndpoint:      "/openvpn/instances/set_static_key",
	DeleteEndpoint:      "/openvpn/instances/del_static_key",
	ReconfigureEndpoint: openvpnReconfigureEndpoint,
	Monad:               "statickey",
}

// Data structs

type StaticKey struct {
	Mode        api.SelectedMap `json:"mode"`
	Key         string          `json:"key"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddStaticKey(ctx context.Context, resource *StaticKey) (string, error) {
	return api.Add(c.Client(), ctx, StaticKeyOpts, resource)
}

func (c *Controller) GetStaticKey(ctx context.Context, id string) (*StaticKey, error) {
	return api.Get(c.Client(), ctx, StaticKeyOpts, &StaticKey{}, id)
}

func (c *Controller) UpdateStaticKey(ctx context.Context, id string, resource *StaticKey) error {
	return api.Update(c.Client(), ctx, StaticKeyOpts, resource, id)
}

func (c *Controller) DeleteStaticKey(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, StaticKeyOpts, id)
}
