// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var FilterOpts = api.ReqOpts{
	AddEndpoint:         "/firewall/filter/addRule",
	GetEndpoint:         "/firewall/filter/getRule",
	UpdateEndpoint:      "/firewall/filter/setRule",
	DeleteEndpoint:      "/firewall/filter/delRule",
	ReconfigureEndpoint: "/firewall/filter/apply",
	Monad:               "rule",
}

// Data structs

type Filter struct {
	Enabled                  string              `json:"enabled"`
	SortOrder                string              `json:"sort_order"`
	Sequence                 string              `json:"sequence"`
	Categories               api.SelectedMapList `json:"categories"`
	NoXMLRPCSync             string              `json:"nosync"`
	Description              string              `json:"description"`
	InvertInterface          string              `json:"interfacenot"`
	Interface                api.SelectedMapList `json:"interface"`
	Quick                    string              `json:"quick"`
	Action                   api.SelectedMap     `json:"action"`
	AllowOptions             string              `json:"allowopts"`
	Direction                api.SelectedMap     `json:"direction"`
	IPProtocol               api.SelectedMap     `json:"ipprotocol"`
	Protocol                 api.SelectedMap     `json:"protocol"`
	ICMPType                 api.SelectedMapList `json:"icmptype"`
	SourceInvert             string              `json:"source_not"`
	SourceNet                string              `json:"source_net"`
	SourcePort               string              `json:"source_port"`
	DestinationInvert        string              `json:"destination_not"`
	DestinationNet           string              `json:"destination_net"`
	DestinationPort          string              `json:"destination_port"`
	Log                      string              `json:"log"`
	TCPFlags                 api.SelectedMapList `json:"tcpflags1"`
	TCPFlagsOutOf            api.SelectedMapList `json:"tcpflags2"`
	Schedule                 api.SelectedMap     `json:"sched"`
	StateType                api.SelectedMap     `json:"statetype"`
	StatePolicy              api.SelectedMap     `json:"state-policy"`
	StateTimeout             string              `json:"statetimeout"`
	AdaptiveTimeoutsStart    string              `json:"adaptivestart"`
	AdaptiveTimeoutsEnd      string              `json:"adaptiveend"`
	MaxStates                string              `json:"max"`
	MaxSourceNodes           string              `json:"max-src-nodes"`
	MaxSourceStates          string              `json:"max-src-states"`
	MaxSourceConnections     string              `json:"max-src-conn"`
	MaxNewConnectionsCount   string              `json:"max-src-conn-rate"`
	MaxNewConnectionsSeconds string              `json:"max-src-conn-rates"`
	OverloadTable            api.SelectedMap     `json:"overload"`
	NoPfsync                 string              `json:"nopfsync"`
	TrafficShaper            api.SelectedMap     `json:"shaper1"`
	TrafficShaperReverse     api.SelectedMap     `json:"shaper2"`
	Gateway                  api.SelectedMap     `json:"gateway"`
	DisableReplyTo           string              `json:"disablereplyto"`
	ReplyTo                  api.SelectedMap     `json:"replyto"`
	MatchPriority            api.SelectedMap     `json:"prio"`
	SetPriority              api.SelectedMap     `json:"set-prio"`
	SetPriorityLowDelay      api.SelectedMap     `json:"set-prio-low"`
	MatchTOS                 api.SelectedMap     `json:"tos"`
	SetLocalTag              string              `json:"tag"`
	MatchLocalTag            string              `json:"tagged"`
}

// CRUD operations

func (c *Controller) AddFilter(ctx context.Context, resource *Filter) (string, error) {
	return api.Add(c.Client(), ctx, FilterOpts, resource)
}

func (c *Controller) GetFilter(ctx context.Context, id string) (*Filter, error) {
	return api.Get(c.Client(), ctx, FilterOpts, &Filter{}, id)
}

func (c *Controller) UpdateFilter(ctx context.Context, id string, resource *Filter) error {
	return api.Update(c.Client(), ctx, FilterOpts, resource, id)
}

func (c *Controller) DeleteFilter(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, FilterOpts, id)
}
