// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type GeoIPSettingsGetResult struct {
	Alias GeoIPSettingsAlias `json:"alias"`
}

type GeoIPSettingsAlias struct {
	GeoIP GeoIPSettings `json:"geoip"`
}

type GeoIPSettings struct {
	Url string `json:"url"`
}

type GeoIPSettingsSetParams struct {
	GeoIP GeoIPSettingsUrl `json:"geoip"`
}

type GeoIPSettingsUrl struct {
	Url string `json:"url"`
}

type ActionResult struct {
	Result string `json:"result"`
}

// GeoIPSettingsGet executes the Get RPC call of the GeoIPSettings controller
func (c *Controller) GeoIPSettingsGet(ctx context.Context) (*GeoIPSettingsGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/alias/getGeoIP",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GeoIPSettingsGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// GeoIPSettingsSet executes the Set RPC call of the GeoIPSettings controller
func (c *Controller) GeoIPSettingsSet(ctx context.Context, alias *GeoIPSettingsSetParams) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["alias"] = alias

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/alias/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}

// GeoIPSettingsUpdate executes the Update RPC call of the GeoIPSettings controller
func (c *Controller) GeoIPSettingsUpdate(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/alias/update/geoip",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Update call failed: %w", err)
	}
	return result, nil
}
