// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var GroupOpts = api.ReqOpts{
	AddEndpoint:         "/firewall/group/addItem",
	GetEndpoint:         "/firewall/group/getItem",
	UpdateEndpoint:      "/firewall/group/setItem",
	DeleteEndpoint:      "/firewall/group/delItem",
	ReconfigureEndpoint: "/firewall/group/reconfigure",
	Monad:               "group",
}

// Data structs

type Group struct {
	Name        string              `json:"ifname"`
	Members     api.SelectedMapList `json:"members"`
	Sequence    string              `json:"sequence"`
	NoGroup     string              `json:"nogroup"`
	Description string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddGroup(ctx context.Context, resource *Group) (string, error) {
	return api.Add(c.Client(), ctx, GroupOpts, resource)
}

func (c *Controller) GetGroup(ctx context.Context, id string) (*Group, error) {
	return api.Get(c.Client(), ctx, GroupOpts, &Group{}, id)
}

func (c *Controller) UpdateGroup(ctx context.Context, id string, resource *Group) error {
	return api.Update(c.Client(), ctx, GroupOpts, resource, id)
}

func (c *Controller) DeleteGroup(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GroupOpts, id)
}
