// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type NATGeneral struct {
	SNATMode api.SelectedMap `json:"snat_mode"`
}

type NATSettings struct {
	General NATGeneral `json:"general"`
}

type NATSettingsMonad struct {
	Filter NATSettings `json:"filter"`
}

// NATSettingsGet executes the Get RPC call of the NATSettings controller
func (c *Controller) NATSettingsGet(ctx context.Context) (*NATSettingsMonad, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/source_nat/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &NATSettingsMonad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// NATSettingsUpdate executes the Update RPC call of the NATSettings controller
func (c *Controller) NATSettingsUpdate(ctx context.Context, filter *NATSettings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["filter"] = filter

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/source_nat/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Update call failed: %w", err)
	}
	return result, nil
}

// NATSettingsApply executes the Apply RPC call of the NATSettings controller
func (c *Controller) NATSettingsApply(ctx context.Context) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/firewall/source_nat/apply",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Apply call failed: %w", err)
	}
	return result, nil
}
