// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var AssignmentOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/assignment/addItem",
	GetEndpoint:         "/interfaces/assignment/getItem",
	UpdateEndpoint:      "/interfaces/assignment/setItem",
	DeleteEndpoint:      "/interfaces/assignment/delItem",
	ReconfigureEndpoint: "/interfaces/assignment/reconfigure",
	Monad:               "interface",
}

// Data structs

type Assignment struct {
	Device      api.SelectedMap `json:"if"`
	Description string          `json:"descr"`
	Lock        string          `json:"lock"`
}

// CRUD operations

func (c *Controller) AddAssignment(ctx context.Context, resource *Assignment) (string, error) {
	return api.Add(c.Client(), ctx, AssignmentOpts, resource)
}

func (c *Controller) GetAssignment(ctx context.Context, id string) (*Assignment, error) {
	return api.Get(c.Client(), ctx, AssignmentOpts, &Assignment{}, id)
}

func (c *Controller) UpdateAssignment(ctx context.Context, id string, resource *Assignment) error {
	return api.Update(c.Client(), ctx, AssignmentOpts, resource, id)
}

func (c *Controller) DeleteAssignment(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AssignmentOpts, id)
}
