// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var BridgeOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/bridge_settings/addItem",
	GetEndpoint:         "/interfaces/bridge_settings/getItem",
	UpdateEndpoint:      "/interfaces/bridge_settings/setItem",
	DeleteEndpoint:      "/interfaces/bridge_settings/delItem",
	ReconfigureEndpoint: "/interfaces/bridge_settings/reconfigure",
	Monad:               "bridge",
}

// Data structs

type Bridge struct {
	Device         string              `json:"bridgeif"`
	Members        api.SelectedMapList `json:"members"`
	LinkLocal      string              `json:"linklocal"`
	EnableStp      string              `json:"enablestp"`
	StpProto       api.SelectedMap     `json:"proto"`
	StpInterfaces  api.SelectedMapList `json:"stp"`
	MaxAge         string              `json:"maxage"`
	ForwardDelay   string              `json:"fwdelay"`
	HoldCount      string              `json:"holdcnt"`
	MaxAddresses   string              `json:"maxaddr"`
	AddressTimeout string              `json:"timeout"`
	SpanInterface  api.SelectedMap     `json:"span"`
	EdgePorts      api.SelectedMapList `json:"edge"`
	AutoEdgePorts  api.SelectedMapList `json:"autoedge"`
	PtpPorts       api.SelectedMapList `json:"ptp"`
	AutoPtpPorts   api.SelectedMapList `json:"autoptp"`
	StaticPorts    api.SelectedMapList `json:"static"`
	PrivatePorts   api.SelectedMapList `json:"private"`
	Description    string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddBridge(ctx context.Context, resource *Bridge) (string, error) {
	return api.Add(c.Client(), ctx, BridgeOpts, resource)
}

func (c *Controller) GetBridge(ctx context.Context, id string) (*Bridge, error) {
	return api.Get(c.Client(), ctx, BridgeOpts, &Bridge{}, id)
}

func (c *Controller) UpdateBridge(ctx context.Context, id string, resource *Bridge) error {
	return api.Update(c.Client(), ctx, BridgeOpts, resource, id)
}

func (c *Controller) DeleteBridge(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BridgeOpts, id)
}
