// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type SearchLaggItem struct {
	Id              string `json:"uuid"`
	Device          string `json:"laggif"`
	Members         string `json:"members"`
	PrimaryMember   string `json:"primary_member"`
	Protocol        string `json:"proto"`
	LACPFastTimeout string `json:"lacp_fast_timeout"`
	UseFlowID       string `json:"use_flowid"`
	HashLayers      string `json:"lagghash"`
	LACPStrict      string `json:"lacp_strict"`
	MTU             string `json:"mtu"`
	Description     string `json:"descr"`
}

type SearchLaggResponse struct {
	Current  int              `json:"current"`
	RowCount int              `json:"rowCount"`
	Total    int              `json:"total"`
	Rows     []SearchLaggItem `json:"rows"`
}

// SearchLagg executes the Lagg RPC call of the Search controller
func (c *Controller) SearchLagg(ctx context.Context, rowCount string) (*SearchLaggResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/interfaces/lagg_settings/search_item",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SearchLaggResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Lagg call failed: %w", err)
	}
	return result, nil
}
