// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var LaggOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/lagg_settings/addItem",
	GetEndpoint:         "/interfaces/lagg_settings/getItem",
	UpdateEndpoint:      "/interfaces/lagg_settings/setItem",
	DeleteEndpoint:      "/interfaces/lagg_settings/delItem",
	ReconfigureEndpoint: "/interfaces/lagg_settings/reconfigure",
	Monad:               "lagg",
}

// Data structs

type Lagg struct {
	Device          string              `json:"laggif"`
	Members         api.SelectedMapList `json:"members"`
	PrimaryMember   api.SelectedMap     `json:"primary_member"`
	Protocol        api.SelectedMap     `json:"proto"`
	LACPFastTimeout string              `json:"lacp_fast_timeout"`
	UseFlowID       api.SelectedMap     `json:"use_flowid"`
	HashLayers      api.SelectedMapList `json:"lagghash"`
	LACPStrict      api.SelectedMap     `json:"lacp_strict"`
	MTU             string              `json:"mtu"`
	Description     string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddLagg(ctx context.Context, resource *Lagg) (string, error) {
	return api.Add(c.Client(), ctx, LaggOpts, resource)
}

func (c *Controller) GetLagg(ctx context.Context, id string) (*Lagg, error) {
	return api.Get(c.Client(), ctx, LaggOpts, &Lagg{}, id)
}

func (c *Controller) UpdateLagg(ctx context.Context, id string, resource *Lagg) error {
	return api.Update(c.Client(), ctx, LaggOpts, resource, id)
}

func (c *Controller) DeleteLagg(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, LaggOpts, id)
}
