// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type InterfaceConfig struct {
	If                                              string            `json:"if,omitempty"`
	Description                                     string            `json:"descr,omitempty"`
	Enable                                          string            `json:"enable,omitempty"`
	Lock                                            string            `json:"lock,omitempty"`
	SpoofMac                                        string            `json:"spoofmac,omitempty"`
	BlockPriv                                       string            `json:"blockpriv,omitempty"`
	BlockBogons                                     string            `json:"blockbogons,omitempty"`
	Promisc                                         string            `json:"promisc,omitempty"`
	Media                                           string            `json:"media,omitempty"`
	MediaOpt                                        string            `json:"mediaopt,omitempty"`
	MTU                                             string            `json:"mtu,omitempty"`
	MSS                                             string            `json:"mss,omitempty"`
	HwSettingsOverwrite                             string            `json:"hw_settings_overwrite,omitempty"`
	DisableChecksumOffloading                       string            `json:"disablechecksumoffloading,omitempty"`
	DisableLargeReceiveOffloading                   string            `json:"disablelargereceiveoffloading,omitempty"`
	DisableSegmentationOffloading                   string            `json:"disablesegmentationoffloading,omitempty"`
	DisableVlanHwfilter                             string            `json:"disablevlanhwfilter,omitempty"`
	IPAddr                                          string            `json:"ipaddr,omitempty"`
	Subnet                                          string            `json:"subnet,omitempty"`
	DHCPHostname                                    string            `json:"dhcphostname,omitempty"`
	AliasAddress                                    string            `json:"alias-address,omitempty"`
	AliasSubnet                                     string            `json:"alias-subnet,omitempty"`
	DHCPRejectFrom                                  string            `json:"dhcprejectfrom,omitempty"`
	DHCPHonourMTU                                   string            `json:"dhcphonourmtu,omitempty"`
	DHCPVlanPrio                                    string            `json:"dhcpvlanprio,omitempty"`
	AdvDHCPPtTimeout                                string            `json:"adv_dhcp_pt_timeout,omitempty"`
	AdvDHCPPtRetry                                  string            `json:"adv_dhcp_pt_retry,omitempty"`
	AdvDHCPPtSelectTimeout                          string            `json:"adv_dhcp_pt_select_timeout,omitempty"`
	AdvDHCPPtReboot                                 string            `json:"adv_dhcp_pt_reboot,omitempty"`
	AdvDHCPPtBackoffCutoff                          string            `json:"adv_dhcp_pt_backoff_cutoff,omitempty"`
	AdvDHCPPtInitialInterval                        string            `json:"adv_dhcp_pt_initial_interval,omitempty"`
	AdvDHCPPtValues                                 string            `json:"adv_dhcp_pt_values,omitempty"`
	AdvDHCPSendOptions                              string            `json:"adv_dhcp_send_options,omitempty"`
	AdvDHCPRequestOptions                           string            `json:"adv_dhcp_request_options,omitempty"`
	AdvDHCPRequiredOptions                          string            `json:"adv_dhcp_required_options,omitempty"`
	AdvDHCPOptionModifiers                          string            `json:"adv_dhcp_option_modifiers,omitempty"`
	AdvDHCPConfigAdvanced                           string            `json:"adv_dhcp_config_advanced,omitempty"`
	AdvDHCPConfigFileOverride                       string            `json:"adv_dhcp_config_file_override,omitempty"`
	AdvDHCPConfigFileOverridePath                   string            `json:"adv_dhcp_config_file_override_path,omitempty"`
	IPAddrV6                                        string            `json:"ipaddrv6,omitempty"`
	DHCP6IAPdLen                                    string            `json:"dhcp6-ia-pd-len,omitempty"`
	DHCP6IAPdSendHint                               string            `json:"dhcp6-ia-pd-send-hint,omitempty"`
	DHCP6PrefixOnly                                 string            `json:"dhcp6prefixonly,omitempty"`
	DHCP6PrefixID                                   string            `json:"dhcp6-prefix-id,omitempty"`
	DHCP6VlanPrio                                   string            `json:"dhcp6vlanprio,omitempty"`
	DHCP6IfID                                       string            `json:"dhcp6_ifid,omitempty"`
	DHCP6NorequestDns                               string            `json:"dhcp6_norequest_dns,omitempty"`
	DHCP6RapidCommit                                string            `json:"dhcp6_rapid_commit,omitempty"`
	DHCP6AssocPd                                    string            `json:"dhcp6_assoc_pd,omitempty"`
	AdvDHCP6InterfaceStatementSendOptions           string            `json:"adv_dhcp6_interface_statement_send_options,omitempty"`
	AdvDHCP6InterfaceStatementRequestOptions        string            `json:"adv_dhcp6_interface_statement_request_options,omitempty"`
	AdvDHCP6InterfaceStatementInformationOnlyEnable string            `json:"adv_dhcp6_interface_statement_information_only_enable,omitempty"`
	AdvDHCP6InterfaceStatementScript                string            `json:"adv_dhcp6_interface_statement_script,omitempty"`
	AdvDHCP6IDAssocStatementAddressEnable           string            `json:"adv_dhcp6_id_assoc_statement_address_enable,omitempty"`
	AdvDHCP6IDAssocStatementAddress                 string            `json:"adv_dhcp6_id_assoc_statement_address,omitempty"`
	AdvDHCP6IDAssocStatementAddressID               string            `json:"adv_dhcp6_id_assoc_statement_address_id,omitempty"`
	AdvDHCP6IDAssocStatementAddressPltime           string            `json:"adv_dhcp6_id_assoc_statement_address_pltime,omitempty"`
	AdvDHCP6IDAssocStatementAddressVltime           string            `json:"adv_dhcp6_id_assoc_statement_address_vltime,omitempty"`
	AdvDHCP6IDAssocStatementPrefixEnable            string            `json:"adv_dhcp6_id_assoc_statement_prefix_enable,omitempty"`
	AdvDHCP6IDAssocStatementPrefix                  string            `json:"adv_dhcp6_id_assoc_statement_prefix,omitempty"`
	AdvDHCP6IDAssocStatementPrefixID                string            `json:"adv_dhcp6_id_assoc_statement_prefix_id,omitempty"`
	AdvDHCP6IDAssocStatementPrefixPltime            string            `json:"adv_dhcp6_id_assoc_statement_prefix_pltime,omitempty"`
	AdvDHCP6IDAssocStatementPrefixVltime            string            `json:"adv_dhcp6_id_assoc_statement_prefix_vltime,omitempty"`
	AdvDHCP6PrefixInterfaceStatementSlaLen          string            `json:"adv_dhcp6_prefix_interface_statement_sla_len,omitempty"`
	AdvDHCP6AuthenticationStatementAuthname         string            `json:"adv_dhcp6_authentication_statement_authname,omitempty"`
	AdvDHCP6AuthenticationStatementProtocol         string            `json:"adv_dhcp6_authentication_statement_protocol,omitempty"`
	AdvDHCP6AuthenticationStatementAlgorithm        string            `json:"adv_dhcp6_authentication_statement_algorithm,omitempty"`
	AdvDHCP6AuthenticationStatementRdm              string            `json:"adv_dhcp6_authentication_statement_rdm,omitempty"`
	AdvDHCP6KeyInfoStatementKeyname                 string            `json:"adv_dhcp6_key_info_statement_keyname,omitempty"`
	AdvDHCP6KeyInfoStatementRealm                   string            `json:"adv_dhcp6_key_info_statement_realm,omitempty"`
	AdvDHCP6KeyInfoStatementKeyid                   string            `json:"adv_dhcp6_key_info_statement_keyid,omitempty"`
	AdvDHCP6KeyInfoStatementSecret                  string            `json:"adv_dhcp6_key_info_statement_secret,omitempty"`
	AdvDHCP6KeyInfoStatementExpire                  string            `json:"adv_dhcp6_key_info_statement_expire,omitempty"`
	AdvDHCP6ConfigAdvanced                          string            `json:"adv_dhcp6_config_advanced,omitempty"`
	AdvDHCP6ConfigFileOverride                      string            `json:"adv_dhcp6_config_file_override,omitempty"`
	AdvDHCP6ConfigFileOverridePath                  string            `json:"adv_dhcp6_config_file_override_path,omitempty"`
	Identifier                                      string            `json:"identifier,omitempty"`
	InternalDynamic                                 string            `json:"internal_dynamic,omitempty"`
	SubnetV6                                        string            `json:"subnetv6,omitempty"`
	GatewayV6                                       string            `json:"gatewayv6,omitempty"`
	Gateway6rd                                      string            `json:"gateway-6rd,omitempty"`
	Prefix6rd                                       string            `json:"prefix-6rd,omitempty"`
	Prefix6rdV4Addr                                 string            `json:"prefix-6rd-v4addr,omitempty"`
	Prefix6rdV4Plen                                 string            `json:"prefix-6rd-v4plen,omitempty"`
	Track6Interface                                 string            `json:"track6-interface,omitempty"`
	Track6PrefixID                                  string            `json:"track6-prefix-id,omitempty"`
	Track6IfID                                      string            `json:"track6_ifid,omitempty"`
	Track6AssocPd                                   string            `json:"track6_assoc_pd,omitempty"`
	DHCPD6Track6AllowOverride                       string            `json:"dhcpd6track6allowoverride,omitempty"`
	Type                                            string            `json:"type,omitempty"`
	Virtual                                         string            `json:"virtual,omitempty"`
	Gateway                                         string            `json:"gateway,omitempty"`
	GatewayInterface                                string            `json:"gateway_interface,omitempty"`
	Wireless                                        InterfaceWireless `json:"wireless,omitempty"`
}

type InterfaceIPv4 struct {
	IPAddr     string `json:"ipaddr,omitempty"`
	Vhid       string `json:"vhid,omitempty"`
	CarpStatus string `json:"status,omitempty"`
	AdvBase    string `json:"advbase,omitempty"`
	AdvSkew    string `json:"advskew,omitempty"`
	Peer       string `json:"peer,omitempty"`
	Peer6      string `json:"peer6,omitempty"`
}

type InterfaceIPv6 struct {
	IPAddr     string `json:"ipaddr,omitempty"`
	Vhid       string `json:"vhid,omitempty"`
	CarpStatus string `json:"status,omitempty"`
	AdvBase    string `json:"advbase,omitempty"`
	AdvSkew    string `json:"advskew,omitempty"`
	Peer       string `json:"peer,omitempty"`
	Peer6      string `json:"peer6,omitempty"`
}

type InterfaceInfo struct {
	Flags             []string        `json:"flags,omitempty"`
	Capabilities      []string        `json:"capabilities,omitempty"`
	Options           []string        `json:"options,omitempty"`
	MacAddr           string          `json:"macaddr,omitempty"`
	SupportedMedia    []string        `json:"supported_media,omitempty"`
	IsPhysical        bool            `json:"is_physical,omitempty"`
	Device            string          `json:"device,omitempty"`
	MTU               string          `json:"mtu,omitempty"`
	MacAddrHw         string          `json:"macaddr_hw,omitempty"`
	Media             string          `json:"media,omitempty"`
	MediaRaw          string          `json:"media_raw,omitempty"`
	Status            string          `json:"status,omitempty"`
	ND6               InterfaceND6    `json:"nd6,omitempty"`
	Routes            []string        `json:"routes,omitempty"`
	Config            InterfaceConfig `json:"config,omitempty"`
	IfctlNameserver   []string        `json:"ifctl.nameserver,omitempty"`
	IfctlRouter       []string        `json:"ifctl.router,omitempty"`
	IfctlPrefix       []string        `json:"ifctl.prefix,omitempty"`
	IfctlSearchdomain []string        `json:"ifctl.searchdomain,omitempty"`
	Identifier        string          `json:"identifier,omitempty"`
	Description       string          `json:"description,omitempty"`
	Enabled           bool            `json:"enabled,omitempty"`
	LinkType          string          `json:"link_type,omitempty"`
	Addr4             string          `json:"addr4,omitempty"`
	Addr6             string          `json:"addr6,omitempty"`
	IPv4              []InterfaceIPv4 `json:"ipv4,omitempty"`
	IPv6              []InterfaceIPv6 `json:"ipv6,omitempty"`
	VLANTag           string          `json:"vlan_tag,omitempty"`
	Gateways          []string        `json:"gateways,omitempty"`
	Groups            []string        `json:"groups,omitempty"`
	VLAN              InterfaceVlan   `json:"vlan,omitempty"`
	LaggProto         string          `json:"laggproto,omitempty"`
	LaggHash          string          `json:"lagghash,omitempty"`
	LaggOptions       string          `json:"laggoptions,omitempty"`
}

type InterfaceND6 struct {
	Flags []string `json:"flags,omitempty"`
}

type InterfaceVlan struct {
	Tag    string `json:"tag,omitempty"`
	Proto  string `json:"proto,omitempty"`
	PCP    string `json:"pcp,omitempty"`
	Parent string `json:"parent,omitempty"`
}

type InterfaceWireless struct {
	Standard                string `json:"standard,omitempty"`
	Mode                    string `json:"mode,omitempty"`
	Protmode                string `json:"protmode,omitempty"`
	SSID                    string `json:"ssid,omitempty"`
	Channel                 string `json:"channel,omitempty"`
	TXPower                 string `json:"txpower,omitempty"`
	Diversity               string `json:"diversity,omitempty"`
	TXAntenna               string `json:"txantenna,omitempty"`
	RXAntenna               string `json:"rxantenna,omitempty"`
	Regdomain               string `json:"regdomain,omitempty"`
	Regcountry              string `json:"regcountry,omitempty"`
	Reglocation             string `json:"reglocation,omitempty"`
	Authmode                string `json:"authmode,omitempty"`
	AuthServerAddr          string `json:"auth_server_addr,omitempty"`
	AuthServerPort          string `json:"auth_server_port,omitempty"`
	AuthServerSharedSecret  string `json:"auth_server_shared_secret,omitempty"`
	AuthServerAddr2         string `json:"auth_server_addr2,omitempty"`
	AuthServerPort2         string `json:"auth_server_port2,omitempty"`
	AuthServerSharedSecret2 string `json:"auth_server_shared_secret2,omitempty"`
	MacACL                  string `json:"mac_acl,omitempty"`
	DebugMode               string `json:"debug_mode,omitempty"`
	MacAddrACL              string `json:"macaddr_acl,omitempty"`
	AuthAlgs                string `json:"auth_algs,omitempty"`
	WPAMode                 string `json:"wpa_mode,omitempty"`
	WPAEAPMethod            string `json:"wpa_eap_method,omitempty"`
	WPAEAPP2Auth            string `json:"wpa_eap_p2_auth,omitempty"`
	WPAKeyMgmt              string `json:"wpa_key_mgmt,omitempty"`
	WPAPairwise             string `json:"wpa_pairwise,omitempty"`
	WPAEAPCACertRef         string `json:"wpa_eap_cacertref,omitempty"`
	WPAEAPCltCertRef        string `json:"wpa_eap_cltcertref,omitempty"`
	WPAGroupRekey           string `json:"wpa_group_rekey,omitempty"`
	WPAGMKRekey             string `json:"wpa_gmk_rekey,omitempty"`
	Identity                string `json:"identity,omitempty"`
	Passphrase              string `json:"passphrase,omitempty"`
	ExtWPASW                string `json:"ext_wpa_sw,omitempty"`
	PersistCommonWireless   string `json:"persistcommonwireless,omitempty"`
	WMEEnable               string `json:"wme_enable,omitempty"`
	APBridgeEnable          string `json:"apbridge_enable,omitempty"`
	HideSSIDEnable          string `json:"hidessid_enable,omitempty"`
	WEPEnable               string `json:"wep_enable,omitempty"`
	PureMode                string `json:"puremode,omitempty"`
	IEEE8021X               string `json:"ieee8021x,omitempty"`
	RSNPreauth              string `json:"rsn_preauth,omitempty"`
	MacACLEnable            string `json:"mac_acl_enable,omitempty"`
	WPAStrictRekey          string `json:"wpa_strict_rekey,omitempty"`
	WPAEnable               string `json:"wpa_enable,omitempty"`
	Key1                    string `json:"key1,omitempty"`
	Key2                    string `json:"key2,omitempty"`
	Key3                    string `json:"key3,omitempty"`
	Key4                    string `json:"key4,omitempty"`
	TXKey                   string `json:"txkey,omitempty"`
}

type InterfacesInfoResponse struct {
	Total    int             `json:"total"`
	RowCount int             `json:"rowCount"`
	Current  int             `json:"current"`
	Rows     []InterfaceInfo `json:"rows"`
}

// OverviewGet executes the Get RPC call of the Overview controller
func (c *Controller) OverviewGet(ctx context.Context) (*InterfacesInfoResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/interfaces/overview/interfaces_info",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &InterfacesInfoResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}
