// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var VxlanOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/vxlan_settings/addItem",
	GetEndpoint:         "/interfaces/vxlan_settings/getItem",
	UpdateEndpoint:      "/interfaces/vxlan_settings/setItem",
	DeleteEndpoint:      "/interfaces/vxlan_settings/delItem",
	ReconfigureEndpoint: "/interfaces/vxlan_settings/reconfigure",
	Monad:               "vxlan",
}

// Data structs

type Vxlan struct {
	DeviceId   string          `json:"deviceId"`
	VxlanId    string          `json:"vxlanid"`
	Local      string          `json:"vxlanlocal"`
	LocalPort  string          `json:"vxlanlocalport"`
	Remote     string          `json:"vxlanremote"`
	RemotePort string          `json:"vxlanremoteport"`
	Group      string          `json:"vxlangroup"`
	Device     api.SelectedMap `json:"vxlandev"`
}

// CRUD operations

func (c *Controller) AddVxlan(ctx context.Context, resource *Vxlan) (string, error) {
	return api.Add(c.Client(), ctx, VxlanOpts, resource)
}

func (c *Controller) GetVxlan(ctx context.Context, id string) (*Vxlan, error) {
	return api.Get(c.Client(), ctx, VxlanOpts, &Vxlan{}, id)
}

func (c *Controller) UpdateVxlan(ctx context.Context, id string, resource *Vxlan) error {
	return api.Update(c.Client(), ctx, VxlanOpts, resource, id)
}

func (c *Controller) DeleteVxlan(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, VxlanOpts, id)
}
