// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package crowdsec

import "github.com/browningluke/opnsense-go/pkg/api"

const crowdsecReconfigureEndpoint = "/crowdsec/service/reconfigure"

// Controller for crowdsec
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
