// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package crowdsec

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type CrowdsecGeneral struct {
	AgentEnabled            string `json:"agent_enabled"`
	LapiEnabled             string `json:"lapi_enabled"`
	FirewallBouncerEnabled  string `json:"firewall_bouncer_enabled"`
	LapiManualConfiguration string `json:"lapi_manual_configuration"`
	LapiListenAddress       string `json:"lapi_listen_address"`
	LapiListenPort          string `json:"lapi_listen_port"`
	RulesEnabled            string `json:"rules_enabled"`
	RulesLog                string `json:"rules_log"`
	RulesTag                string `json:"rules_tag"`
	EnrollKey               string `json:"enroll_key"`
	CrowdsecFirewallVerbose string `json:"crowdsec_firewall_verbose"`
}

type GeneralGetResult struct {
	General CrowdsecGeneral `json:"general"`
}

type GeneralSetResult struct {
	Result string `json:"result"`
}

// GeneralGet executes the Get RPC call of the General controller
func (c *Controller) GeneralGet(ctx context.Context) (*GeneralGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/crowdsec/general/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GeneralGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// GeneralSet executes the Set RPC call of the General controller
func (c *Controller) GeneralSet(ctx context.Context, general *CrowdsecGeneral) (*GeneralSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["general"] = general

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/crowdsec/general/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GeneralSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
