// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var AclOpts = api.ReqOpts{
	AddEndpoint:         "/bind/acl/add_acl",
	GetEndpoint:         "/bind/acl/get_acl",
	UpdateEndpoint:      "/bind/acl/set_acl",
	DeleteEndpoint:      "/bind/acl/del_acl",
	ReconfigureEndpoint: bindReconfigureEndpoint,
	Monad:               "acl",
}

// Data structs

type Acl struct {
	Name     string              `json:"name"`
	Enabled  string              `json:"enabled"`
	Networks api.SelectedMapList `json:"networks"`
}

// CRUD operations

func (c *Controller) AddAcl(ctx context.Context, resource *Acl) (string, error) {
	return api.Add(c.Client(), ctx, AclOpts, resource)
}

func (c *Controller) GetAcl(ctx context.Context, id string) (*Acl, error) {
	return api.Get(c.Client(), ctx, AclOpts, &Acl{}, id)
}

func (c *Controller) UpdateAcl(ctx context.Context, id string, resource *Acl) error {
	return api.Update(c.Client(), ctx, AclOpts, resource, id)
}

func (c *Controller) DeleteAcl(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AclOpts, id)
}
