// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import "github.com/browningluke/opnsense-go/pkg/api"

const bindReconfigureEndpoint = "/bind/service/reconfigure"

// Controller for bind
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
