// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var RecordOpts = api.ReqOpts{
	AddEndpoint:         "/bind/record/add_record",
	GetEndpoint:         "/bind/record/get_record",
	UpdateEndpoint:      "/bind/record/set_record",
	DeleteEndpoint:      "/bind/record/del_record",
	ReconfigureEndpoint: bindReconfigureEndpoint,
	Monad:               "record",
}

// Data structs

type Record struct {
	Domain  api.SelectedMap `json:"domain"`
	Enabled string          `json:"enabled"`
	Name    string          `json:"name"`
	Type    api.SelectedMap `json:"type"`
	Value   string          `json:"value"`
}

// CRUD operations

func (c *Controller) AddRecord(ctx context.Context, resource *Record) (string, error) {
	return api.Add(c.Client(), ctx, RecordOpts, resource)
}

func (c *Controller) GetRecord(ctx context.Context, id string) (*Record, error) {
	return api.Get(c.Client(), ctx, RecordOpts, &Record{}, id)
}

func (c *Controller) UpdateRecord(ctx context.Context, id string, resource *Record) error {
	return api.Update(c.Client(), ctx, RecordOpts, resource, id)
}

func (c *Controller) DeleteRecord(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, RecordOpts, id)
}
