// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type BFDGetResult struct {
	BFD QuaggaBFD `json:"bfd"`
}

type BFDSetResult struct {
	Result string `json:"result"`
}

type QuaggaBFD struct {
	Enabled string `json:"enabled"`
}

// BFDGet executes the Get RPC call of the BFD controller
func (c *Controller) BFDGet(ctx context.Context) (*BFDGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/bfd/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &BFDGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// BFDSet executes the Set RPC call of the BFD controller
func (c *Controller) BFDSet(ctx context.Context, bfd *QuaggaBFD) (*BFDSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["bfd"] = bfd

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/bfd/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &BFDSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
