// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var BFDSettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/bfd/get",
	UpdateEndpoint:      "/quagga/bfd/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "bfd",
}

// Data structs

type BFDSettings struct {
	Enabled string `json:"enabled"`
}

// CRUD operations

func (c *Controller) GetBFDSettings(ctx context.Context) (*BFDSettings, error) {
	return api.Get(c.Client(), ctx, BFDSettingsOpts, &BFDSettings{}, "")
}

func (c *Controller) UpdateBFDSettings(ctx context.Context, resource *BFDSettings) error {
	return api.Update(c.Client(), ctx, BFDSettingsOpts, resource, "")
}
