// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var BFDNeighborOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/bfd/add_neighbor",
	GetEndpoint:         "/quagga/bfd/get_neighbor",
	UpdateEndpoint:      "/quagga/bfd/set_neighbor",
	DeleteEndpoint:      "/quagga/bfd/del_neighbor",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "neighbor",
}

// Data structs

type BFDNeighbor struct {
	Enabled          string          `json:"enabled"`
	Description      string          `json:"description"`
	Address          string          `json:"address"`
	MultiHop         string          `json:"multihop"`
	LocalAddress     string          `json:"localaddress"`
	InterfaceName    api.SelectedMap `json:"interfacename"`
	DetectMultiplier string          `json:"detect_multiplier"`
	ReceiveInterval  string          `json:"receive_interval"`
	TransmitInterval string          `json:"transmit_interval"`
}

// CRUD operations

func (c *Controller) AddBFDNeighbor(ctx context.Context, resource *BFDNeighbor) (string, error) {
	return api.Add(c.Client(), ctx, BFDNeighborOpts, resource)
}

func (c *Controller) GetBFDNeighbor(ctx context.Context, id string) (*BFDNeighbor, error) {
	return api.Get(c.Client(), ctx, BFDNeighborOpts, &BFDNeighbor{}, id)
}

func (c *Controller) UpdateBFDNeighbor(ctx context.Context, id string, resource *BFDNeighbor) error {
	return api.Update(c.Client(), ctx, BFDNeighborOpts, resource, id)
}

func (c *Controller) DeleteBFDNeighbor(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BFDNeighborOpts, id)
}
