// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type BGPGetResult struct {
	BGP QuaggaBGP `json:"bgp"`
}

type BGPSetResult struct {
	Result string `json:"result"`
}

type QuaggaBGP struct {
	Enabled            string              `json:"enabled"`
	ASNumber           string              `json:"asnumber"`
	Distance           string              `json:"distance"`
	RouterID           string              `json:"routerid"`
	Graceful           string              `json:"graceful"`
	NetworkImportCheck string              `json:"networkimportcheck"`
	EnforceFirstAS     string              `json:"enforce_first_as"`
	LogNeighborChanges string              `json:"logneighborchanges"`
	Networks           api.SelectedMapList `json:"networks"`
	BestPath           api.SelectedMapList `json:"bestpath"`
	MaximumPaths       string              `json:"maximumpaths"`
	MaximumPathsIBGP   string              `json:"maximumpathsibgp"`
}

// BGPGet executes the Get RPC call of the BGP controller
func (c *Controller) BGPGet(ctx context.Context) (*BGPGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/bgp/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &BGPGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// BGPSet executes the Set RPC call of the BGP controller
func (c *Controller) BGPSet(ctx context.Context, bgp *QuaggaBGP) (*BGPSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["bgp"] = bgp

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/bgp/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &BGPSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
