// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var BGPRedistributionOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/bgp/addRedistribution",
	GetEndpoint:         "/quagga/bgp/getRedistribution",
	UpdateEndpoint:      "/quagga/bgp/setRedistribution",
	DeleteEndpoint:      "/quagga/bgp/delRedistribution",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "redistribution",
}

// Data structs

type BGPRedistribution struct {
	Enabled      string          `json:"enabled"`
	Description  string          `json:"description"`
	Redistribute api.SelectedMap `json:"redistribute"`
	RouteMap     api.SelectedMap `json:"linkedRoutemap"`
}

// CRUD operations

func (c *Controller) AddBGPRedistribution(ctx context.Context, resource *BGPRedistribution) (string, error) {
	return api.Add(c.Client(), ctx, BGPRedistributionOpts, resource)
}

func (c *Controller) GetBGPRedistribution(ctx context.Context, id string) (*BGPRedistribution, error) {
	return api.Get(c.Client(), ctx, BGPRedistributionOpts, &BGPRedistribution{}, id)
}

func (c *Controller) UpdateBGPRedistribution(ctx context.Context, id string, resource *BGPRedistribution) error {
	return api.Update(c.Client(), ctx, BGPRedistributionOpts, resource, id)
}

func (c *Controller) DeleteBGPRedistribution(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BGPRedistributionOpts, id)
}
