// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var BGPPeerGroupOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/bgp/add_peergroup",
	GetEndpoint:         "/quagga/bgp/get_peergroup",
	UpdateEndpoint:      "/quagga/bgp/set_peergroup",
	DeleteEndpoint:      "/quagga/bgp/del_peergroup",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "peergroup",
}

// Data structs

type BGPPeerGroup struct {
	Enabled          string              `json:"enabled"`
	Name             string              `json:"name"`
	RemoteASMode     api.SelectedMap     `json:"remote_as_mode"`
	RemoteAS         string              `json:"remoteas"`
	Family           api.SelectedMap     `json:"family"`
	ListenRanges     api.SelectedMapList `json:"listenranges"`
	UpdateSource     api.SelectedMap     `json:"updatesource"`
	NextHopSelf      string              `json:"nexthopself"`
	DefaultOriginate string              `json:"defaultoriginate"`
	PrefixListIn     api.SelectedMap     `json:"linkedPrefixlistIn"`
	PrefixListOut    api.SelectedMap     `json:"linkedPrefixlistOut"`
	RouteMapIn       api.SelectedMap     `json:"linkedRoutemapIn"`
	RouteMapOut      api.SelectedMap     `json:"linkedRoutemapOut"`
}

// CRUD operations

func (c *Controller) AddBGPPeerGroup(ctx context.Context, resource *BGPPeerGroup) (string, error) {
	return api.Add(c.Client(), ctx, BGPPeerGroupOpts, resource)
}

func (c *Controller) GetBGPPeerGroup(ctx context.Context, id string) (*BGPPeerGroup, error) {
	return api.Get(c.Client(), ctx, BGPPeerGroupOpts, &BGPPeerGroup{}, id)
}

func (c *Controller) UpdateBGPPeerGroup(ctx context.Context, id string, resource *BGPPeerGroup) error {
	return api.Update(c.Client(), ctx, BGPPeerGroupOpts, resource, id)
}

func (c *Controller) DeleteBGPPeerGroup(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BGPPeerGroupOpts, id)
}
