// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var BGPSettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/bgp/get",
	UpdateEndpoint:      "/quagga/bgp/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "bgp",
}

// Data structs

type BGPSettings struct {
	Enabled            string              `json:"enabled"`
	ASNumber           string              `json:"asnumber"`
	Distance           string              `json:"distance"`
	RouterID           string              `json:"routerid"`
	Graceful           string              `json:"graceful"`
	NetworkImportCheck string              `json:"networkimportcheck"`
	EnforceFirstAS     string              `json:"enforce_first_as"`
	LogNeighborChanges string              `json:"logneighborchanges"`
	Networks           api.SelectedMapList `json:"networks"`
	BestPath           api.SelectedMapList `json:"bestpath"`
	MaximumPaths       string              `json:"maximumpaths"`
	MaximumPathsIBGP   string              `json:"maximumpathsibgp"`
}

// CRUD operations

func (c *Controller) GetBGPSettings(ctx context.Context) (*BGPSettings, error) {
	return api.Get(c.Client(), ctx, BGPSettingsOpts, &BGPSettings{}, "")
}

func (c *Controller) UpdateBGPSettings(ctx context.Context, resource *BGPSettings) error {
	return api.Update(c.Client(), ctx, BGPSettingsOpts, resource, "")
}
