// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var GeneralSettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/general/get",
	UpdateEndpoint:      "/quagga/general/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "general",
}

// Data structs

type GeneralSettings struct {
	Enabled       string              `json:"enabled"`
	Daemons       api.SelectedMapList `json:"daemons"`
	ManualConfig  string              `json:"manual_config"`
	Profile       api.SelectedMap     `json:"profile"`
	EnableCARP    string              `json:"enablecarp"`
	EnableSyslog  string              `json:"enablesyslog"`
	EnableSNMP    string              `json:"enablesnmp"`
	SyslogLevel   api.SelectedMap     `json:"sysloglevel"`
	FirewallRules string              `json:"fwrules"`
}

// CRUD operations

func (c *Controller) GetGeneralSettings(ctx context.Context) (*GeneralSettings, error) {
	return api.Get(c.Client(), ctx, GeneralSettingsOpts, &GeneralSettings{}, "")
}

func (c *Controller) UpdateGeneralSettings(ctx context.Context, resource *GeneralSettings) error {
	return api.Update(c.Client(), ctx, GeneralSettingsOpts, resource, "")
}
