// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type GeneralGetResult struct {
	General QuaggaGeneral `json:"general"`
}

type GeneralSetResult struct {
	Result string `json:"result"`
}

type QuaggaGeneral struct {
	Enabled      string          `json:"enabled"`
	Profile      api.SelectedMap `json:"profile"`
	EnableCarp   string          `json:"enablecarp"`
	EnableSyslog string          `json:"enablesyslog"`
	EnableSNMP   string          `json:"enablesnmp"`
	SyslogLevel  api.SelectedMap `json:"sysloglevel"`
	FWRules      string          `json:"fwrules"`
}

// GeneralGet executes the Get RPC call of the General controller
func (c *Controller) GeneralGet(ctx context.Context) (*GeneralGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/general/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GeneralGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// GeneralSet executes the Set RPC call of the General controller
func (c *Controller) GeneralSet(ctx context.Context, general *QuaggaGeneral) (*GeneralSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["general"] = general

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/general/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GeneralSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
