// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPF6InterfaceOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospf6settings/add_interface",
	GetEndpoint:         "/quagga/ospf6settings/get_interface",
	UpdateEndpoint:      "/quagga/ospf6settings/set_interface",
	DeleteEndpoint:      "/quagga/ospf6settings/del_interface",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "interface",
}

// Data structs

type OSPF6Interface struct {
	Enabled            string          `json:"enabled"`
	InterfaceName      api.SelectedMap `json:"interfacename"`
	Area               string          `json:"area"`
	Passive            string          `json:"passive"`
	Cost               string          `json:"cost"`
	CostDemoted        string          `json:"cost_demoted"`
	CARPDependOn       api.SelectedMap `json:"carp_depend_on"`
	HelloInterval      string          `json:"hellointerval"`
	DeadInterval       string          `json:"deadinterval"`
	RetransmitInterval string          `json:"retransmitinterval"`
	TransmitDelay      string          `json:"transmitdelay"`
	Priority           string          `json:"priority"`
	BFD                string          `json:"bfd"`
	NetworkType        api.SelectedMap `json:"networktype"`
}

// CRUD operations

func (c *Controller) AddOSPF6Interface(ctx context.Context, resource *OSPF6Interface) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6InterfaceOpts, resource)
}

func (c *Controller) GetOSPF6Interface(ctx context.Context, id string) (*OSPF6Interface, error) {
	return api.Get(c.Client(), ctx, OSPF6InterfaceOpts, &OSPF6Interface{}, id)
}

func (c *Controller) UpdateOSPF6Interface(ctx context.Context, id string, resource *OSPF6Interface) error {
	return api.Update(c.Client(), ctx, OSPF6InterfaceOpts, resource, id)
}

func (c *Controller) DeleteOSPF6Interface(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6InterfaceOpts, id)
}
