// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFAreaOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospfsettings/add_area",
	GetEndpoint:         "/quagga/ospfsettings/get_area",
	UpdateEndpoint:      "/quagga/ospfsettings/set_area",
	DeleteEndpoint:      "/quagga/ospfsettings/del_area",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "area",
}

// Data structs

type OSPFArea struct {
	Enabled string          `json:"enabled"`
	AreaID  string          `json:"id"`
	Type    api.SelectedMap `json:"type"`
}

// CRUD operations

func (c *Controller) AddOSPFArea(ctx context.Context, resource *OSPFArea) (string, error) {
	return api.Add(c.Client(), ctx, OSPFAreaOpts, resource)
}

func (c *Controller) GetOSPFArea(ctx context.Context, id string) (*OSPFArea, error) {
	return api.Get(c.Client(), ctx, OSPFAreaOpts, &OSPFArea{}, id)
}

func (c *Controller) UpdateOSPFArea(ctx context.Context, id string, resource *OSPFArea) error {
	return api.Update(c.Client(), ctx, OSPFAreaOpts, resource, id)
}

func (c *Controller) DeleteOSPFArea(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFAreaOpts, id)
}
