// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPF6RedistributionOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospf6settings/add_redistribution",
	GetEndpoint:         "/quagga/ospf6settings/get_redistribution",
	UpdateEndpoint:      "/quagga/ospf6settings/set_redistribution",
	DeleteEndpoint:      "/quagga/ospf6settings/del_redistribution",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "redistribution",
}

// Data structs

type OSPF6Redistribution struct {
	Enabled        string          `json:"enabled"`
	Description    string          `json:"description"`
	Redistribute   api.SelectedMap `json:"redistribute"`
	LinkedRouteMap api.SelectedMap `json:"linkedRoutemap"`
}

// CRUD operations

func (c *Controller) AddOSPF6Redistribution(ctx context.Context, resource *OSPF6Redistribution) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6RedistributionOpts, resource)
}

func (c *Controller) GetOSPF6Redistribution(ctx context.Context, id string) (*OSPF6Redistribution, error) {
	return api.Get(c.Client(), ctx, OSPF6RedistributionOpts, &OSPF6Redistribution{}, id)
}

func (c *Controller) UpdateOSPF6Redistribution(ctx context.Context, id string, resource *OSPF6Redistribution) error {
	return api.Update(c.Client(), ctx, OSPF6RedistributionOpts, resource, id)
}

func (c *Controller) DeleteOSPF6Redistribution(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6RedistributionOpts, id)
}
