// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPF6PrefixListOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospf6settings/add_prefixlist",
	GetEndpoint:         "/quagga/ospf6settings/get_prefixlist",
	UpdateEndpoint:      "/quagga/ospf6settings/set_prefixlist",
	DeleteEndpoint:      "/quagga/ospf6settings/del_prefixlist",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "prefixlist",
}

// Data structs

type OSPF6PrefixList struct {
	Enabled        string          `json:"enabled"`
	Name           string          `json:"name"`
	SequenceNumber string          `json:"seqnumber"`
	Action         api.SelectedMap `json:"action"`
	Network        string          `json:"network"`
}

// CRUD operations

func (c *Controller) AddOSPF6PrefixList(ctx context.Context, resource *OSPF6PrefixList) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6PrefixListOpts, resource)
}

func (c *Controller) GetOSPF6PrefixList(ctx context.Context, id string) (*OSPF6PrefixList, error) {
	return api.Get(c.Client(), ctx, OSPF6PrefixListOpts, &OSPF6PrefixList{}, id)
}

func (c *Controller) UpdateOSPF6PrefixList(ctx context.Context, id string, resource *OSPF6PrefixList) error {
	return api.Update(c.Client(), ctx, OSPF6PrefixListOpts, resource, id)
}

func (c *Controller) DeleteOSPF6PrefixList(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6PrefixListOpts, id)
}
