// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFRedistributionOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospfsettings/addRedistribution",
	GetEndpoint:         "/quagga/ospfsettings/getRedistribution",
	UpdateEndpoint:      "/quagga/ospfsettings/setRedistribution",
	DeleteEndpoint:      "/quagga/ospfsettings/delRedistribution",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "redistribution",
}

// Data structs

type OSPFRedistribution struct {
	Enabled      string          `json:"enabled"`
	Description  string          `json:"description"`
	Redistribute api.SelectedMap `json:"redistribute"`
	RouteMap     api.SelectedMap `json:"linkedRoutemap"`
}

// CRUD operations

func (c *Controller) AddOSPFRedistribution(ctx context.Context, resource *OSPFRedistribution) (string, error) {
	return api.Add(c.Client(), ctx, OSPFRedistributionOpts, resource)
}

func (c *Controller) GetOSPFRedistribution(ctx context.Context, id string) (*OSPFRedistribution, error) {
	return api.Get(c.Client(), ctx, OSPFRedistributionOpts, &OSPFRedistribution{}, id)
}

func (c *Controller) UpdateOSPFRedistribution(ctx context.Context, id string, resource *OSPFRedistribution) error {
	return api.Update(c.Client(), ctx, OSPFRedistributionOpts, resource, id)
}

func (c *Controller) DeleteOSPFRedistribution(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFRedistributionOpts, id)
}
