// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFNetworkOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospfsettings/add_network",
	GetEndpoint:         "/quagga/ospfsettings/get_network",
	UpdateEndpoint:      "/quagga/ospfsettings/set_network",
	DeleteEndpoint:      "/quagga/ospfsettings/del_network",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "network",
}

// Data structs

type OSPFNetwork struct {
	Enabled             string          `json:"enabled"`
	IPAddr              string          `json:"ipaddr"`
	Area                string          `json:"area"`
	NetMask             string          `json:"netmask"`
	AreaRange           string          `json:"arearange"`
	LinkedPrefixListIn  api.SelectedMap `json:"linkedPrefixlistIn"`
	LinkedPrefixListOut api.SelectedMap `json:"linkedPrefixlistOut"`
}

// CRUD operations

func (c *Controller) AddOSPFNetwork(ctx context.Context, resource *OSPFNetwork) (string, error) {
	return api.Add(c.Client(), ctx, OSPFNetworkOpts, resource)
}

func (c *Controller) GetOSPFNetwork(ctx context.Context, id string) (*OSPFNetwork, error) {
	return api.Get(c.Client(), ctx, OSPFNetworkOpts, &OSPFNetwork{}, id)
}

func (c *Controller) UpdateOSPFNetwork(ctx context.Context, id string, resource *OSPFNetwork) error {
	return api.Update(c.Client(), ctx, OSPFNetworkOpts, resource, id)
}

func (c *Controller) DeleteOSPFNetwork(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFNetworkOpts, id)
}
