// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type OSPFGetResult struct {
	OSPF QuaggaOSPF `json:"ospf"`
}

type OSPFSetResult struct {
	Result string `json:"result"`
}

type QuaggaOSPF struct {
	Enabled             string              `json:"enabled"`
	CARPDemote          string              `json:"carp_demote"`
	RouterID            string              `json:"routerid"`
	CostReference       string              `json:"costreference"`
	LogAdjacencyChanges string              `json:"logadjacencychanges"`
	Originate           string              `json:"originate"`
	OriginateAlways     string              `json:"originatealways"`
	OriginateMetric     string              `json:"originatemetric"`
	PassiveInterfaces   api.SelectedMapList `json:"passiveinterfaces"`
}

// OSPFGet executes the Get RPC call of the OSPF controller
func (c *Controller) OSPFGet(ctx context.Context) (*OSPFGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/ospfsettings/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &OSPFGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// OSPFSet executes the Set RPC call of the OSPF controller
func (c *Controller) OSPFSet(ctx context.Context, ospf *QuaggaOSPF) (*OSPFSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ospf"] = ospf

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/ospfsettings/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &OSPFSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
