// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFNeighborOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospfsettings/add_neighbor",
	GetEndpoint:         "/quagga/ospfsettings/get_neighbor",
	UpdateEndpoint:      "/quagga/ospfsettings/set_neighbor",
	DeleteEndpoint:      "/quagga/ospfsettings/del_neighbor",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "neighbor",
}

// Data structs

type OSPFNeighbor struct {
	Enabled      string `json:"enabled"`
	Description  string `json:"description"`
	Address      string `json:"address"`
	PollInterval string `json:"pollinterval"`
	Priority     string `json:"priority"`
}

// CRUD operations

func (c *Controller) AddOSPFNeighbor(ctx context.Context, resource *OSPFNeighbor) (string, error) {
	return api.Add(c.Client(), ctx, OSPFNeighborOpts, resource)
}

func (c *Controller) GetOSPFNeighbor(ctx context.Context, id string) (*OSPFNeighbor, error) {
	return api.Get(c.Client(), ctx, OSPFNeighborOpts, &OSPFNeighbor{}, id)
}

func (c *Controller) UpdateOSPFNeighbor(ctx context.Context, id string, resource *OSPFNeighbor) error {
	return api.Update(c.Client(), ctx, OSPFNeighborOpts, resource, id)
}

func (c *Controller) DeleteOSPFNeighbor(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFNeighborOpts, id)
}
