// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPF6SettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/ospf6settings/get",
	UpdateEndpoint:      "/quagga/ospf6settings/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "ospf6",
}

// Data structs

type OSPF6Settings struct {
	Enabled         string `json:"enabled"`
	CarpDemote      string `json:"carp_demote"`
	RouterID        string `json:"routerid"`
	Originate       string `json:"originate"`
	OriginateAlways string `json:"originatealways"`
	OriginateMetric string `json:"originatemetric"`
}

// CRUD operations

func (c *Controller) GetOSPF6Settings(ctx context.Context) (*OSPF6Settings, error) {
	return api.Get(c.Client(), ctx, OSPF6SettingsOpts, &OSPF6Settings{}, "")
}

func (c *Controller) UpdateOSPF6Settings(ctx context.Context, resource *OSPF6Settings) error {
	return api.Update(c.Client(), ctx, OSPF6SettingsOpts, resource, "")
}
