// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type OSPF6GetResult struct {
	OSPF6 QuaggaOSPF6 `json:"ospf6"`
}

type OSPF6SetResult struct {
	Result string `json:"result"`
}

type QuaggaOSPF6 struct {
	Enabled         string `json:"enabled"`
	CARPDemote      string `json:"carp_demote"`
	RouterID        string `json:"routerid"`
	Originate       string `json:"originate"`
	OriginateAlways string `json:"originatealways"`
	OriginateMetric string `json:"originatemetric"`
}

// OSPF6Get executes the Get RPC call of the OSPF6 controller
func (c *Controller) OSPF6Get(ctx context.Context) (*OSPF6GetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/ospf6settings/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &OSPF6GetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// OSPF6Set executes the Set RPC call of the OSPF6 controller
func (c *Controller) OSPF6Set(ctx context.Context, ospf6 *QuaggaOSPF6) (*OSPF6SetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ospf6"] = ospf6

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/ospf6settings/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &OSPF6SetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
