// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFRouteMapOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospfsettings/add_routemap",
	GetEndpoint:         "/quagga/ospfsettings/get_routemap",
	UpdateEndpoint:      "/quagga/ospfsettings/set_routemap",
	DeleteEndpoint:      "/quagga/ospfsettings/del_routemap",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "routemap",
}

// Data structs

type OSPFRouteMap struct {
	Enabled    string          `json:"enabled"`
	Name       string          `json:"name"`
	Action     api.SelectedMap `json:"action"`
	RouteMapID string          `json:"id"`
	PrefixList api.SelectedMap `json:"match2"`
	Set        string          `json:"set"`
}

// CRUD operations

func (c *Controller) AddOSPFRouteMap(ctx context.Context, resource *OSPFRouteMap) (string, error) {
	return api.Add(c.Client(), ctx, OSPFRouteMapOpts, resource)
}

func (c *Controller) GetOSPFRouteMap(ctx context.Context, id string) (*OSPFRouteMap, error) {
	return api.Get(c.Client(), ctx, OSPFRouteMapOpts, &OSPFRouteMap{}, id)
}

func (c *Controller) UpdateOSPFRouteMap(ctx context.Context, id string, resource *OSPFRouteMap) error {
	return api.Update(c.Client(), ctx, OSPFRouteMapOpts, resource, id)
}

func (c *Controller) DeleteOSPFRouteMap(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFRouteMapOpts, id)
}
