// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPF6RouteMapOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospf6settings/add_routemap",
	GetEndpoint:         "/quagga/ospf6settings/get_routemap",
	UpdateEndpoint:      "/quagga/ospf6settings/set_routemap",
	DeleteEndpoint:      "/quagga/ospf6settings/del_routemap",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "routemap",
}

// Data structs

type OSPF6RouteMap struct {
	Enabled    string          `json:"enabled"`
	Name       string          `json:"name"`
	Action     api.SelectedMap `json:"action"`
	RouteMapID string          `json:"id"`
	PrefixList api.SelectedMap `json:"match2"`
	Set        string          `json:"set"`
}

// CRUD operations

func (c *Controller) AddOSPF6RouteMap(ctx context.Context, resource *OSPF6RouteMap) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6RouteMapOpts, resource)
}

func (c *Controller) GetOSPF6RouteMap(ctx context.Context, id string) (*OSPF6RouteMap, error) {
	return api.Get(c.Client(), ctx, OSPF6RouteMapOpts, &OSPF6RouteMap{}, id)
}

func (c *Controller) UpdateOSPF6RouteMap(ctx context.Context, id string, resource *OSPF6RouteMap) error {
	return api.Update(c.Client(), ctx, OSPF6RouteMapOpts, resource, id)
}

func (c *Controller) DeleteOSPF6RouteMap(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6RouteMapOpts, id)
}
