// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPF6NetworkOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospf6settings/add_network",
	GetEndpoint:         "/quagga/ospf6settings/get_network",
	UpdateEndpoint:      "/quagga/ospf6settings/set_network",
	DeleteEndpoint:      "/quagga/ospf6settings/del_network",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "network",
}

// Data structs

type OSPF6Network struct {
	Enabled             string          `json:"enabled"`
	IPAddr              string          `json:"ipaddr"`
	NetMask             string          `json:"netmask"`
	Area                string          `json:"area"`
	AreaRange           string          `json:"arearange"`
	LinkedPrefixListIn  api.SelectedMap `json:"linkedPrefixlistIn"`
	LinkedPrefixListOut api.SelectedMap `json:"linkedPrefixlistOut"`
}

// CRUD operations

func (c *Controller) AddOSPF6Network(ctx context.Context, resource *OSPF6Network) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6NetworkOpts, resource)
}

func (c *Controller) GetOSPF6Network(ctx context.Context, id string) (*OSPF6Network, error) {
	return api.Get(c.Client(), ctx, OSPF6NetworkOpts, &OSPF6Network{}, id)
}

func (c *Controller) UpdateOSPF6Network(ctx context.Context, id string, resource *OSPF6Network) error {
	return api.Update(c.Client(), ctx, OSPF6NetworkOpts, resource, id)
}

func (c *Controller) DeleteOSPF6Network(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6NetworkOpts, id)
}
