// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFPrefixListOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/ospfsettings/add_prefixlist",
	GetEndpoint:         "/quagga/ospfsettings/get_prefixlist",
	UpdateEndpoint:      "/quagga/ospfsettings/set_prefixlist",
	DeleteEndpoint:      "/quagga/ospfsettings/del_prefixlist",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "prefixlist",
}

// Data structs

type OSPFPrefixList struct {
	Enabled        string          `json:"enabled"`
	Name           string          `json:"name"`
	SequenceNumber string          `json:"seqnumber"`
	Action         api.SelectedMap `json:"action"`
	Network        string          `json:"network"`
}

// CRUD operations

func (c *Controller) AddOSPFPrefixList(ctx context.Context, resource *OSPFPrefixList) (string, error) {
	return api.Add(c.Client(), ctx, OSPFPrefixListOpts, resource)
}

func (c *Controller) GetOSPFPrefixList(ctx context.Context, id string) (*OSPFPrefixList, error) {
	return api.Get(c.Client(), ctx, OSPFPrefixListOpts, &OSPFPrefixList{}, id)
}

func (c *Controller) UpdateOSPFPrefixList(ctx context.Context, id string, resource *OSPFPrefixList) error {
	return api.Update(c.Client(), ctx, OSPFPrefixListOpts, resource, id)
}

func (c *Controller) DeleteOSPFPrefixList(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFPrefixListOpts, id)
}
