// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var OSPFSettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/ospfsettings/get",
	UpdateEndpoint:      "/quagga/ospfsettings/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "ospf",
}

// Data structs

type OSPFSettings struct {
	Enabled             string              `json:"enabled"`
	CarpDemote          string              `json:"carp_demote"`
	RouterID            string              `json:"routerid"`
	CostReference       string              `json:"costreference"`
	LogAdjacencyChanges string              `json:"logadjacencychanges"`
	Originate           string              `json:"originate"`
	OriginateAlways     string              `json:"originatealways"`
	OriginateMetric     string              `json:"originatemetric"`
	PassiveInterfaces   api.SelectedMapList `json:"passiveinterfaces"`
}

// CRUD operations

func (c *Controller) GetOSPFSettings(ctx context.Context) (*OSPFSettings, error) {
	return api.Get(c.Client(), ctx, OSPFSettingsOpts, &OSPFSettings{}, "")
}

func (c *Controller) UpdateOSPFSettings(ctx context.Context, resource *OSPFSettings) error {
	return api.Update(c.Client(), ctx, OSPFSettingsOpts, resource, "")
}
