// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type QuaggaRIP struct {
	Enabled           string              `json:"enabled"`
	Version           string              `json:"version"`
	Networks          api.SelectedMapList `json:"networks"`
	PassiveInterfaces api.SelectedMapList `json:"passiveinterfaces"`
	Redistribute      api.SelectedMapList `json:"redistribute"`
	DefaultMetric     string              `json:"defaultmetric"`
}

type RIPGetResult struct {
	RIP QuaggaRIP `json:"rip"`
}

type RIPSetResult struct {
	Result string `json:"result"`
}

// RIPGet executes the Get RPC call of the RIP controller
func (c *Controller) RIPGet(ctx context.Context) (*RIPGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/rip/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &RIPGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// RIPSet executes the Set RPC call of the RIP controller
func (c *Controller) RIPSet(ctx context.Context, rip *QuaggaRIP) (*RIPSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["rip"] = rip

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/rip/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &RIPSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
