// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var RIPSettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/rip/get",
	UpdateEndpoint:      "/quagga/rip/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "rip",
}

// Data structs

type RIPSettings struct {
	Enabled           string              `json:"enabled"`
	Version           string              `json:"version"`
	Networks          api.SelectedMapList `json:"networks"`
	PassiveInterfaces api.SelectedMapList `json:"passiveinterfaces"`
	Redistribute      api.SelectedMapList `json:"redistribute"`
	DefaultMetric     string              `json:"defaultmetric"`
}

// CRUD operations

func (c *Controller) GetRIPSettings(ctx context.Context) (*RIPSettings, error) {
	return api.Get(c.Client(), ctx, RIPSettingsOpts, &RIPSettings{}, "")
}

func (c *Controller) UpdateRIPSettings(ctx context.Context, resource *RIPSettings) error {
	return api.Update(c.Client(), ctx, RIPSettingsOpts, resource, "")
}
