// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type QuaggaStatic struct {
	Enabled string `json:"enabled"`
}

type StaticGetResult struct {
	Static QuaggaStatic `json:"staticd"`
}

type StaticSetResult struct {
	Result string `json:"result"`
}

// StaticGet executes the Get RPC call of the Static controller
func (c *Controller) StaticGet(ctx context.Context) (*StaticGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/static/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &StaticGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// StaticSet executes the Set RPC call of the Static controller
func (c *Controller) StaticSet(ctx context.Context, staticd *QuaggaStatic) (*StaticSetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["staticd"] = staticd

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/quagga/static/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &StaticSetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
