// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var StaticSettingsOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/quagga/static/get",
	UpdateEndpoint:      "/quagga/static/set",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "staticd",
}

// Data structs

type StaticSettings struct {
	Enabled string `json:"enabled"`
}

// CRUD operations

func (c *Controller) GetStaticSettings(ctx context.Context) (*StaticSettings, error) {
	return api.Get(c.Client(), ctx, StaticSettingsOpts, &StaticSettings{}, "")
}

func (c *Controller) UpdateStaticSettings(ctx context.Context, resource *StaticSettings) error {
	return api.Update(c.Client(), ctx, StaticSettingsOpts, resource, "")
}
