// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var StaticRouteOpts = api.ReqOpts{
	AddEndpoint:         "/quagga/static/add_route",
	GetEndpoint:         "/quagga/static/get_route",
	UpdateEndpoint:      "/quagga/static/set_route",
	DeleteEndpoint:      "/quagga/static/del_route",
	ReconfigureEndpoint: quaggaReconfigureEndpoint,
	Monad:               "route",
}

// Data structs

type StaticRoute struct {
	Enabled       string          `json:"enabled"`
	Network       string          `json:"network"`
	Gateway       string          `json:"gateway"`
	InterfaceName api.SelectedMap `json:"interfacename"`
	BFD           string          `json:"bfd"`
}

// CRUD operations

func (c *Controller) AddStaticRoute(ctx context.Context, resource *StaticRoute) (string, error) {
	return api.Add(c.Client(), ctx, StaticRouteOpts, resource)
}

func (c *Controller) GetStaticRoute(ctx context.Context, id string) (*StaticRoute, error) {
	return api.Get(c.Client(), ctx, StaticRouteOpts, &StaticRoute{}, id)
}

func (c *Controller) UpdateStaticRoute(ctx context.Context, id string, resource *StaticRoute) error {
	return api.Update(c.Client(), ctx, StaticRouteOpts, resource, id)
}

func (c *Controller) DeleteStaticRoute(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, StaticRouteOpts, id)
}
