// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ids

import "github.com/browningluke/opnsense-go/pkg/api"

const idsReconfigureEndpoint = "/ids/service/reconfigure"

// Controller for ids
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
