// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ids

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var PolicyOpts = api.ReqOpts{
	AddEndpoint:         "/ids/settings/add_policy",
	GetEndpoint:         "/ids/settings/get_policy",
	UpdateEndpoint:      "/ids/settings/set_policy",
	DeleteEndpoint:      "/ids/settings/del_policy",
	ReconfigureEndpoint: "",
	Monad:               "policy",
}

// Data structs

type Policy struct {
	Enabled     string              `json:"enabled"`
	Priority    string              `json:"prio"`
	Action      api.SelectedMapList `json:"action"`
	Rulesets    api.SelectedMapList `json:"rulesets"`
	Content     api.SelectedMapList `json:"content"`
	NewAction   api.SelectedMap     `json:"new_action"`
	Description string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddPolicy(ctx context.Context, resource *Policy) (string, error) {
	return api.Add(c.Client(), ctx, PolicyOpts, resource)
}

func (c *Controller) GetPolicy(ctx context.Context, id string) (*Policy, error) {
	return api.Get(c.Client(), ctx, PolicyOpts, &Policy{}, id)
}

func (c *Controller) UpdatePolicy(ctx context.Context, id string, resource *Policy) error {
	return api.Update(c.Client(), ctx, PolicyOpts, resource, id)
}

func (c *Controller) DeletePolicy(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PolicyOpts, id)
}
