// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ids

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var PolicyRuleOpts = api.ReqOpts{
	AddEndpoint:         "/ids/settings/add_policy_rule",
	GetEndpoint:         "/ids/settings/get_policy_rule",
	UpdateEndpoint:      "/ids/settings/set_policy_rule",
	DeleteEndpoint:      "/ids/settings/del_policy_rule",
	ReconfigureEndpoint: "",
	Monad:               "rule",
}

// Data structs

type PolicyRule struct {
	SID     string          `json:"sid"`
	Enabled string          `json:"enabled"`
	Action  api.SelectedMap `json:"action"`
	Message string          `json:"msg"`
	Source  string          `json:"source"`
}

// CRUD operations

func (c *Controller) AddPolicyRule(ctx context.Context, resource *PolicyRule) (string, error) {
	return api.Add(c.Client(), ctx, PolicyRuleOpts, resource)
}

func (c *Controller) GetPolicyRule(ctx context.Context, id string) (*PolicyRule, error) {
	return api.Get(c.Client(), ctx, PolicyRuleOpts, &PolicyRule{}, id)
}

func (c *Controller) UpdatePolicyRule(ctx context.Context, id string, resource *PolicyRule) error {
	return api.Update(c.Client(), ctx, PolicyRuleOpts, resource, id)
}

func (c *Controller) DeletePolicyRule(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PolicyRuleOpts, id)
}
