// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ids

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type Ruleset struct {
	Filename    string `json:"filename"`
	Enabled     string `json:"enabled"`
	Description string `json:"description"`
}

type ToggleResult struct {
	Status string `json:"status"`
}

// RulesetGet executes the Get RPC call of the Ruleset controller
func (c *Controller) RulesetGet(ctx context.Context, id string) (*Ruleset, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, id)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/ids/settings/get_ruleset",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Ruleset{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// RulesetToggle executes the Toggle RPC call of the Ruleset controller
func (c *Controller) RulesetToggle(ctx context.Context, filename string, enabled string) (*ToggleResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, filename)

	callParams = append(callParams, enabled)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/ids/settings/toggle_ruleset",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ToggleResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Toggle call failed: %w", err)
	}
	return result, nil
}
