// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ids

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type General struct {
	Enabled    string              `json:"enabled"`
	Mode       api.SelectedMap     `json:"mode"`
	Interfaces api.SelectedMapList `json:"interfaces"`
	HomeNet    api.SelectedMapList `json:"homenet"`
	Promisc    string              `json:"promisc"`
}

type Settings struct {
	General General `json:"general"`
}

type SettingsMonad struct {
	Ids Settings `json:"ids"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsMonad, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/ids/settings/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsMonad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// SettingsUpdate executes the Update RPC call of the Settings controller
func (c *Controller) SettingsUpdate(ctx context.Context, ids *Settings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ids"] = ids

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/ids/settings/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Update call failed: %w", err)
	}
	return result, nil
}
