// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ids

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var UserRuleOpts = api.ReqOpts{
	AddEndpoint:         "/ids/settings/add_user_rule",
	GetEndpoint:         "/ids/settings/get_user_rule",
	UpdateEndpoint:      "/ids/settings/set_user_rule",
	DeleteEndpoint:      "/ids/settings/del_user_rule",
	ReconfigureEndpoint: "",
	Monad:               "rule",
}

// Data structs

type UserRule struct {
	Enabled     string          `json:"enabled"`
	Source      string          `json:"source"`
	Destination string          `json:"destination"`
	Fingerprint string          `json:"fingerprint"`
	Description string          `json:"description"`
	Action      api.SelectedMap `json:"action"`
	Bypass      string          `json:"bypass"`
}

// CRUD operations

func (c *Controller) AddUserRule(ctx context.Context, resource *UserRule) (string, error) {
	return api.Add(c.Client(), ctx, UserRuleOpts, resource)
}

func (c *Controller) GetUserRule(ctx context.Context, id string) (*UserRule, error) {
	return api.Get(c.Client(), ctx, UserRuleOpts, &UserRule{}, id)
}

func (c *Controller) UpdateUserRule(ctx context.Context, id string, resource *UserRule) error {
	return api.Update(c.Client(), ctx, UserRuleOpts, resource, id)
}

func (c *Controller) DeleteUserRule(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, UserRuleOpts, id)
}
