// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dyndns

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var AccountOpts = api.ReqOpts{
	AddEndpoint:         "/dyndns/accounts/add_item",
	GetEndpoint:         "/dyndns/accounts/get_item",
	UpdateEndpoint:      "/dyndns/accounts/set_item",
	DeleteEndpoint:      "/dyndns/accounts/del_item",
	ReconfigureEndpoint: dyndnsReconfigureEndpoint,
	Monad:               "account",
}

// Data structs

type Account struct {
	Enabled        string              `json:"enabled"`
	Service        api.SelectedMap     `json:"service"`
	Protocol       api.SelectedMap     `json:"protocol"`
	Server         string              `json:"server"`
	Username       string              `json:"username"`
	Password       string              `json:"password"`
	ResourceId     string              `json:"resourceId"`
	Hostnames      api.SelectedMapList `json:"hostnames"`
	Wildcard       string              `json:"wildcard"`
	Zone           string              `json:"zone"`
	Checkip        api.SelectedMap     `json:"checkip"`
	DynIpv6Host    string              `json:"dynipv6host"`
	CheckipTimeout string              `json:"checkip_timeout"`
	ForceSsl       string              `json:"force_ssl"`
	Ttl            string              `json:"ttl"`
	Interface      api.SelectedMap     `json:"interface"`
	Description    string              `json:"description"`
	CurrentIp      string              `json:"current_ip"`
	CurrentMtime   string              `json:"current_mtime"`
}

// CRUD operations

func (c *Controller) AddAccount(ctx context.Context, resource *Account) (string, error) {
	return api.Add(c.Client(), ctx, AccountOpts, resource)
}

func (c *Controller) GetAccount(ctx context.Context, id string) (*Account, error) {
	return api.Get(c.Client(), ctx, AccountOpts, &Account{}, id)
}

func (c *Controller) UpdateAccount(ctx context.Context, id string, resource *Account) error {
	return api.Update(c.Client(), ctx, AccountOpts, resource, id)
}

func (c *Controller) DeleteAccount(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AccountOpts, id)
}
