// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dyndns

import "github.com/browningluke/opnsense-go/pkg/api"

const dyndnsReconfigureEndpoint = "/dyndns/service/reconfigure"

// Controller for dyndns
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
