// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package diagnostics

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type ActionResult struct {
	Status string `json:"status"`
}

type CacheStat struct {
	Pkts           int64  `json:"Pkts"`
	If             string `json:"if"`
	SrcIPAddresses int64  `json:"SrcIPaddresses"`
	DstIPAddresses int64  `json:"DstIPaddresses"`
}

type Capture struct {
	Interfaces api.SelectedMapList `json:"interfaces"`
	EgressOnly api.SelectedMapList `json:"egress_only"`
	Version    api.SelectedMap     `json:"version"`
	Targets    api.SelectedMapList `json:"targets"`
}

type Collect struct {
	Enable string `json:"enable"`
}

type IsEnabledResult struct {
	Netflow int64 `json:"netflow"`
	Local   int64 `json:"local"`
}

type Netflow struct {
	Capture         Capture `json:"capture"`
	Collect         Collect `json:"collect"`
	ActiveTimeout   string  `json:"activeTimeout"`
	InactiveTimeout string  `json:"inactiveTimeout"`
}

type NetflowMonad struct {
	Netflow Netflow `json:"netflow"`
}

type Result struct {
	Result string `json:"result"`
}

type StatusResult struct {
	Status     string `json:"status"`
	Collectors string `json:"collectors,omitempty"`
}

// NetflowGetConfig executes the GetConfig RPC call of the Netflow controller
func (c *Controller) NetflowGetConfig(ctx context.Context) (*NetflowMonad, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/diagnostics/netflow/getconfig",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &NetflowMonad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GetConfig call failed: %w", err)
	}
	return result, nil
}

// NetflowSetConfig executes the SetConfig RPC call of the Netflow controller
func (c *Controller) NetflowSetConfig(ctx context.Context, netflow *Netflow) (*Result, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["netflow"] = netflow

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/diagnostics/netflow/setconfig",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("SetConfig call failed: %w", err)
	}
	return result, nil
}

// NetflowReconfigure executes the Reconfigure RPC call of the Netflow controller
func (c *Controller) NetflowReconfigure(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/diagnostics/netflow/reconfigure",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reconfigure call failed: %w", err)
	}
	return result, nil
}

// NetflowIsEnabled executes the IsEnabled RPC call of the Netflow controller
func (c *Controller) NetflowIsEnabled(ctx context.Context) (*IsEnabledResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/diagnostics/netflow/is_enabled",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &IsEnabledResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("IsEnabled call failed: %w", err)
	}
	return result, nil
}

// NetflowStatus executes the Status RPC call of the Netflow controller
func (c *Controller) NetflowStatus(ctx context.Context) (*StatusResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/diagnostics/netflow/status",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &StatusResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Status call failed: %w", err)
	}
	return result, nil
}

// NetflowCacheStats executes the CacheStats RPC call of the Netflow controller
func (c *Controller) NetflowCacheStats(ctx context.Context) (*CacheStats, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/diagnostics/netflow/cache_stats",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CacheStats{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("CacheStats call failed: %w", err)
	}
	return result, nil
}
