// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var GroupOpts = api.ReqOpts{
	AddEndpoint:         "/auth/group/add",
	GetEndpoint:         "/auth/group/get",
	UpdateEndpoint:      "/auth/group/set",
	DeleteEndpoint:      "/auth/group/del",
	ReconfigureEndpoint: "",
	Monad:               "group",
}

// Data structs

type Group struct {
	GroupId        string              `json:"gid"`
	Name           string              `json:"name"`
	Scope          string              `json:"scope,omitempty"`
	Description    string              `json:"description"`
	Priviledge     api.SelectedMapList `json:"priv"`
	Member         api.SelectedMap     `json:"member"`
	SourceNetworks api.SelectedMap     `json:"source_networks"`
}

// CRUD operations

func (c *Controller) AddGroup(ctx context.Context, resource *Group) (string, error) {
	return api.Add(c.Client(), ctx, GroupOpts, resource)
}

func (c *Controller) GetGroup(ctx context.Context, id string) (*Group, error) {
	return api.Get(c.Client(), ctx, GroupOpts, &Group{}, id)
}

func (c *Controller) UpdateGroup(ctx context.Context, id string, resource *Group) error {
	return api.Update(c.Client(), ctx, GroupOpts, resource, id)
}

func (c *Controller) DeleteGroup(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GroupOpts, id)
}
