// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type PrivilegeGetAllItemResult struct {
	Id     string   `json:"id"`
	Name   string   `json:"name"`
	Match  string   `json:"match"`
	Users  []string `json:"users"`
	Groups []string `json:"groups"`
}

type PrivilegeGetAllResult struct {
	Total    int                         `json:"total"`
	RowCount int                         `json:"rowCount"`
	Current  int                         `json:"current"`
	Rows     []PrivilegeGetAllItemResult `json:"rows"`
}

// PrivilegeGetAll executes the GetAll RPC call of the Privilege controller
func (c *Controller) PrivilegeGetAll(ctx context.Context) (*PrivilegeGetAllResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/auth/priv/search",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &PrivilegeGetAllResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GetAll call failed: %w", err)
	}
	return result, nil
}
