// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type PrivilegeGetItem struct {
	Id     string              `json:"id"`
	Users  api.SelectedMapList `json:"users"`
	Groups api.SelectedMapList `json:"groups"`
}

type PrivilegeGetItemWrapper struct {
	Item PrivilegeGetItem `json:"priv"`
}

// PrivilegeGetItem executes the GetItem RPC call of the Privilege controller
func (c *Controller) PrivilegeGetItem(ctx context.Context, id string) (*PrivilegeGetItemWrapper, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, id)

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/auth/priv/get_item",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &PrivilegeGetItemWrapper{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GetItem call failed: %w", err)
	}
	return result, nil
}
