// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type NewOtpSeedResult struct {
	Seed     string `json:"seed"`
	OtpQrUri string `json:"otp_uri_template"`
}

// UserNewOtpSeed executes the NewOtpSeed RPC call of the User controller
func (c *Controller) UserNewOtpSeed(ctx context.Context) (*NewOtpSeedResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/auth/user/new_otp_seed",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &NewOtpSeedResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("NewOtpSeed call failed: %w", err)
	}
	return result, nil
}
