// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package routes

import "github.com/browningluke/opnsense-go/pkg/api"

const routesReconfigureEndpoint = "/routes/routes/reconfigure"

// Controller for routes
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
