// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package cron

import "github.com/browningluke/opnsense-go/pkg/api"

const cronReconfigureEndpoint = "/cron/service/reconfigure"

// Controller for cron
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
