// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package cron

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var JobOpts = api.ReqOpts{
	AddEndpoint:         "/cron/settings/addJob",
	GetEndpoint:         "/cron/settings/getJob",
	UpdateEndpoint:      "/cron/settings/setJob",
	DeleteEndpoint:      "/cron/settings/delJob",
	ReconfigureEndpoint: cronReconfigureEndpoint,
	Monad:               "job",
}

// Data structs

type Job struct {
	Enabled     string          `json:"enabled"`
	Minutes     string          `json:"minutes"`
	Hours       string          `json:"hours"`
	Days        string          `json:"days"`
	Months      string          `json:"months"`
	Weekdays    string          `json:"weekdays"`
	Who         string          `json:"who"`
	Command     api.SelectedMap `json:"command"`
	Parameters  string          `json:"parameters"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddJob(ctx context.Context, resource *Job) (string, error) {
	return api.Add(c.Client(), ctx, JobOpts, resource)
}

func (c *Controller) GetJob(ctx context.Context, id string) (*Job, error) {
	return api.Get(c.Client(), ctx, JobOpts, &Job{}, id)
}

func (c *Controller) UpdateJob(ctx context.Context, id string, resource *Job) error {
	return api.Update(c.Client(), ctx, JobOpts, resource, id)
}

func (c *Controller) DeleteJob(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, JobOpts, id)
}
