// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var BootOpts = api.ReqOpts{
	AddEndpoint:         "/dnsmasq/settings/add_boot",
	GetEndpoint:         "/dnsmasq/settings/get_boot",
	UpdateEndpoint:      "/dnsmasq/settings/set_boot",
	DeleteEndpoint:      "/dnsmasq/settings/del_boot",
	ReconfigureEndpoint: dnsmasqReconfigureEndpoint,
	Monad:               "boot",
}

// Data structs

type Boot struct {
	Interface     api.SelectedMap     `json:"interface"`
	Tag           api.SelectedMapList `json:"tag"`
	Filename      string              `json:"filename"`
	Servername    string              `json:"servername"`
	ServerAddress string              `json:"address"`
	Description   string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddBoot(ctx context.Context, resource *Boot) (string, error) {
	return api.Add(c.Client(), ctx, BootOpts, resource)
}

func (c *Controller) GetBoot(ctx context.Context, id string) (*Boot, error) {
	return api.Get(c.Client(), ctx, BootOpts, &Boot{}, id)
}

func (c *Controller) UpdateBoot(ctx context.Context, id string, resource *Boot) error {
	return api.Update(c.Client(), ctx, BootOpts, resource, id)
}

func (c *Controller) DeleteBoot(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BootOpts, id)
}
