// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import "github.com/browningluke/opnsense-go/pkg/api"

const dnsmasqReconfigureEndpoint = "/dnsmasq/service/reconfigure"

// Controller for dnsmasq
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
