// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var DomainOpts = api.ReqOpts{
	AddEndpoint:         "/dnsmasq/settings/add_domain",
	GetEndpoint:         "/dnsmasq/settings/get_domain",
	UpdateEndpoint:      "/dnsmasq/settings/set_domain",
	DeleteEndpoint:      "/dnsmasq/settings/del_domain",
	ReconfigureEndpoint: dnsmasqReconfigureEndpoint,
	Monad:               "domainoverride",
}

// Data structs

type Domain struct {
	Sequence      string          `json:"sequence"`
	Domain        string          `json:"domain"`
	FirewallAlias api.SelectedMap `json:"ipset"`
	SourceIp      string          `json:"srcip"`
	Port          string          `json:"port"`
	Ip            string          `json:"ip"`
	Description   string          `json:"descr"`
}

// CRUD operations

func (c *Controller) AddDomain(ctx context.Context, resource *Domain) (string, error) {
	return api.Add(c.Client(), ctx, DomainOpts, resource)
}

func (c *Controller) GetDomain(ctx context.Context, id string) (*Domain, error) {
	return api.Get(c.Client(), ctx, DomainOpts, &Domain{}, id)
}

func (c *Controller) UpdateDomain(ctx context.Context, id string, resource *Domain) error {
	return api.Update(c.Client(), ctx, DomainOpts, resource, id)
}

func (c *Controller) DeleteDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, DomainOpts, id)
}
