// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type GeneralDHCPSettings struct {
	InterfaceNoDhcp       api.SelectedMapList `json:"no_interface"`
	FQDN                  string              `json:"fqdn"`
	DefaultDomain         string              `json:"domain"`
	MaxLeases             string              `json:"lease_max"`
	Authoritative         string              `json:"authoritative"`
	ReplyDelay            string              `json:"reply_delay"`
	RegisterFirewallRules string              `json:"default_fw_rules"`
	RouterAdvertisements  string              `json:"enable_ra"`
	DisableHASync         string              `json:"nosync"`
}

type GeneralSettings struct {
	IsEnabled                               string              `json:"enable"`
	Interface                               api.SelectedMapList `json:"interface"`
	StrictInterfaceBinding                  string              `json:"strictbind"`
	DNS_Port                                string              `json:"port"`
	DNS_DNSSEC                              string              `json:"dnssec"`
	DNS_NoHostLookup                        string              `json:"no_hosts"`
	DNS_LogDnsQueries                       string              `json:"log_queries"`
	DNS_MaxConcurrentQueries                string              `json:"dns_forward_max"`
	DNS_CacheSize                           string              `json:"cache_size"`
	DNS_LocalEntryTTL                       string              `json:"local_ttl"`
	DNS_NoIdent                             string              `json:"no_ident"`
	DNS_QF_QuerySequentially                string              `json:"strict_order"`
	DNS_QF_RequireDomain                    string              `json:"domain_needed"`
	DNS_QF_DoNotForwardSystemDNS            string              `json:"no_resolv"`
	DNS_QF_DoNotForwardPrivateReverseLookup string              `json:"no_private_reverse"`
	DNS_QF_AddMac                           api.SelectedMap     `json:"add_mac"`
	DNS_QF_AddSubnet                        string              `json:"add_subnet"`
	DNS_QF_StripSubnet                      string              `json:"strip_subnet"`
	DHCPSettings                            GeneralDHCPSettings `json:"dhcp"`
	Legacy_RegisterISCDhcp4Leases           string              `json:"regdhcp"`
	Legacy_DhcpDomainOverride               string              `json:"regdhcpdomain"`
	Legacy_RegisterDhcpStaticMappings       string              `json:"regdhcpstatic"`
	Legacy_PreferDhcp                       string              `json:"dhcpfirst"`
}

type GeneralSettingsWrapper struct {
	Dnsmasq GeneralSettings `json:"dnsmasq"`
}

// GeneralSettingsGet executes the Get RPC call of the GeneralSettings controller
func (c *Controller) GeneralSettingsGet(ctx context.Context) (*GeneralSettingsWrapper, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/get",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &GeneralSettingsWrapper{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// GeneralSettingsSet executes the Set RPC call of the GeneralSettings controller
func (c *Controller) GeneralSettingsSet(ctx context.Context, dnsmasq *GeneralSettings) (*api.ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["dnsmasq"] = dnsmasq

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/set",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}
