// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var HostOpts = api.ReqOpts{
	AddEndpoint:         "/dnsmasq/settings/add_host",
	GetEndpoint:         "/dnsmasq/settings/get_host",
	UpdateEndpoint:      "/dnsmasq/settings/set_host",
	DeleteEndpoint:      "/dnsmasq/settings/del_host",
	ReconfigureEndpoint: dnsmasqReconfigureEndpoint,
	Monad:               "host",
}

// Data structs

type Host struct {
	Hostname          string              `json:"host"`
	Domain            string              `json:"domain"`
	IsLocalDomain     string              `json:"local"`
	IpAddresses       api.SelectedMapList `json:"ip"`
	AliasRecords      api.SelectedMapList `json:"aliases"`
	CnameRecords      api.SelectedMapList `json:"cnames"`
	ClientId          string              `json:"client_id"`
	HardwareAddresses api.SelectedMapList `json:"hwaddr"`
	Tagset            api.SelectedMap     `json:"set_tag"`
	IsIgnored         string              `json:"ignore"`
	Description       string              `json:"descr"`
	Comments          string              `json:"comments"`
}

// CRUD operations

func (c *Controller) AddHost(ctx context.Context, resource *Host) (string, error) {
	return api.Add(c.Client(), ctx, HostOpts, resource)
}

func (c *Controller) GetHost(ctx context.Context, id string) (*Host, error) {
	return api.Get(c.Client(), ctx, HostOpts, &Host{}, id)
}

func (c *Controller) UpdateHost(ctx context.Context, id string, resource *Host) error {
	return api.Update(c.Client(), ctx, HostOpts, resource, id)
}

func (c *Controller) DeleteHost(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, HostOpts, id)
}
