// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var OptionOpts = api.ReqOpts{
	AddEndpoint:         "/dnsmasq/settings/add_option",
	GetEndpoint:         "/dnsmasq/settings/get_option",
	UpdateEndpoint:      "/dnsmasq/settings/set_option",
	DeleteEndpoint:      "/dnsmasq/settings/del_option",
	ReconfigureEndpoint: dnsmasqReconfigureEndpoint,
	Monad:               "option",
}

// Data structs

type Option struct {
	Type        api.SelectedMap     `json:"type"`
	OptionV4    api.SelectedMap     `json:"option"`
	OptionV6    api.SelectedMap     `json:"option6"`
	Interface   api.SelectedMap     `json:"interface"`
	Tag         api.SelectedMapList `json:"tag"`
	TagSet      api.SelectedMap     `json:"set_tag"`
	Value       string              `json:"value"`
	Force       string              `json:"force"`
	Description string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddOption(ctx context.Context, resource *Option) (string, error) {
	return api.Add(c.Client(), ctx, OptionOpts, resource)
}

func (c *Controller) GetOption(ctx context.Context, id string) (*Option, error) {
	return api.Get(c.Client(), ctx, OptionOpts, &Option{}, id)
}

func (c *Controller) UpdateOption(ctx context.Context, id string, resource *Option) error {
	return api.Update(c.Client(), ctx, OptionOpts, resource, id)
}

func (c *Controller) DeleteOption(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OptionOpts, id)
}
