// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var RangeOpts = api.ReqOpts{
	AddEndpoint:         "/dnsmasq/settings/add_range",
	GetEndpoint:         "/dnsmasq/settings/get_range",
	UpdateEndpoint:      "/dnsmasq/settings/set_range",
	DeleteEndpoint:      "/dnsmasq/settings/del_range",
	ReconfigureEndpoint: dnsmasqReconfigureEndpoint,
	Monad:               "range",
}

// Data structs

type Range struct {
	Interface        api.SelectedMap `json:"interface"`
	Tags             api.SelectedMap `json:"set_tag"`
	StartAddress     string          `json:"start_addr"`
	EndAddress       string          `json:"end_addr"`
	SubnetMask       string          `json:"subnet_mask"`
	Constructor      api.SelectedMap `json:"constructor"`
	Mode             api.SelectedMap `json:"mode"`
	PrefixLength     string          `json:"prefix_len"`
	LeaseTime        string          `json:"lease_time"`
	DomainType       api.SelectedMap `json:"domain_type"`
	Domain           string          `json:"domain"`
	DisableHASync    string          `json:"nosync"`
	RaMode           api.SelectedMap `json:"ra_mode"`
	RaPriority       api.SelectedMap `json:"ra_priority"`
	RaMTU            string          `json:"ra_mtu"`
	RaInterval       string          `json:"ra_interval"`
	RaRouterLifetime string          `json:"ra_router_lifetime"`
	Description      string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddRange(ctx context.Context, resource *Range) (string, error) {
	return api.Add(c.Client(), ctx, RangeOpts, resource)
}

func (c *Controller) GetRange(ctx context.Context, id string) (*Range, error) {
	return api.Get(c.Client(), ctx, RangeOpts, &Range{}, id)
}

func (c *Controller) UpdateRange(ctx context.Context, id string, resource *Range) error {
	return api.Update(c.Client(), ctx, RangeOpts, resource, id)
}

func (c *Controller) DeleteRange(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, RangeOpts, id)
}
