// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type SearchBootItem struct {
	Id            string `json:"uuid"`
	InterfaceId   string `json:"interface"`
	Interface     string `json:"%interface"`
	TagIds        string `json:"tag"`
	Tags          string `json:"%tag"`
	Filename      string `json:"filename"`
	Servername    string `json:"servername"`
	ServerAddress string `json:"address"`
	Description   string `json:"description"`
}

type SearchBootResponse struct {
	Current  int              `json:"current"`
	RowCount int              `json:"rowCount"`
	Total    int              `json:"total"`
	Rows     []SearchBootItem `json:"rows"`
}

type SearchDomainItem struct {
	Id              string `json:"uuid"`
	Sequence        string `json:"sequence"`
	Domain          string `json:"domain"`
	FirewallAliasId string `json:"ipset"`
	FirewallAlias   string `json:"%ipset"`
	IP              string `json:"ip"`
	Port            string `json:"port"`
	SourceIp        string `json:"srcip"`
	Description     string `json:"descr"`
}

type SearchDomainResponse struct {
	Current  int                `json:"current"`
	RowCount int                `json:"rowCount"`
	Total    int                `json:"total"`
	Rows     []SearchDomainItem `json:"rows"`
}

type SearchHostItem struct {
	Id           string `json:"uuid"`
	Host         string `json:"host"`
	Domain       string `json:"domain"`
	IsLocal      string `json:"local"`
	IPs          string `json:"ip"`
	Aliases      string `json:"aliases"`
	Cnames       string `json:"cnames"`
	ClientId     string `json:"client_id"`
	MacAddresses string `json:"hwaddr"`
	LeaseTime    string `json:"lease_time"`
	TagId        string `json:"set_tag"`
	Tag          string `json:"%set_tag"`
	IsIgnored    string `json:"ignore"`
	Description  string `json:"descr"`
	Comments     string `json:"comments"`
}

type SearchHostResponse struct {
	Current  int              `json:"current"`
	RowCount int              `json:"rowCount"`
	Total    int              `json:"total"`
	Rows     []SearchHostItem `json:"rows"`
}

type SearchOptionItem struct {
	Id          string `json:"uuid"`
	TypeId      string `json:"type"`
	Type        string `json:"%type"`
	OptionV4Id  string `json:"option"`
	OptionV4    string `json:"%option"`
	OptionV6Id  string `json:"option6"`
	OptionV6    string `json:"%option6"`
	InterfaceId string `json:"interface"`
	Interface   string `json:"%interface"`
	TagIds      string `json:"tag"`
	Tags        string `json:"%tag"`
	Tag         string `json:"set_tag"`
	Value       string `json:"value"`
	Force       string `json:"force"`
	Description string `json:"description"`
}

type SearchOptionResponse struct {
	Current  int                `json:"current"`
	RowCount int                `json:"rowCount"`
	Total    int                `json:"total"`
	Rows     []SearchOptionItem `json:"rows"`
}

type SearchRangeItem struct {
	Id               string `json:"uuid"`
	InterfaceId      string `json:"interface"`
	Interface        string `json:"%interface"`
	Tags             string `json:"set_tag"`
	StartAddress     string `json:"start_addr"`
	EndAddress       string `json:"end_addr"`
	SubnetMask       string `json:"subnet_mask"`
	ConstructorId    string `json:"constructor"`
	Constructor      string `json:"%constructor"`
	Mode             string `json:"mode"`
	IPv6PrefixLength string `json:"prefix_len"`
	LeaseTime        string `json:"lease_time"`
	DomainTypeId     string `json:"domain_type"`
	DomainType       string `json:"%domain_type"`
	Domain           string `json:"domain"`
	DisableHASync    string `json:"nosycn"`
	Description      string `json:"description"`
	RaPriorityId     string `json:"ra_priority"`
	RaPriority       string `json:"%ra_priority"`
	RaMTU            string `json:"ra_mtu"`
	RaInterval       string `json:"ra_interval"`
	RaRouterLifetime string `json:"ra_router_lifetime"`
}

type SearchRangeResponse struct {
	Current  int               `json:"current"`
	RowCount int               `json:"rowCount"`
	Total    int               `json:"total"`
	Rows     []SearchRangeItem `json:"rows"`
}

type SearchTagItem struct {
	Id  string `json:"uuid"`
	Tag string `json:"tag"`
}

type SearchTagResponse struct {
	Current  int             `json:"current"`
	RowCount int             `json:"rowCount"`
	Total    int             `json:"total"`
	Rows     []SearchTagItem `json:"rows"`
}

// SearchHost executes the Host RPC call of the Search controller
func (c *Controller) SearchHost(ctx context.Context, rowCount string) (*SearchHostResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/search_host",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchHostResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Host call failed: %w", err)
	}
	return result, nil
}

// SearchDomain executes the Domain RPC call of the Search controller
func (c *Controller) SearchDomain(ctx context.Context, rowCount string) (*SearchDomainResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/search_domain",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchDomainResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Domain call failed: %w", err)
	}
	return result, nil
}

// SearchRange executes the Range RPC call of the Search controller
func (c *Controller) SearchRange(ctx context.Context, rowCount string) (*SearchRangeResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/search_range",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchRangeResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Range call failed: %w", err)
	}
	return result, nil
}

// SearchOption executes the Option RPC call of the Search controller
func (c *Controller) SearchOption(ctx context.Context, rowCount string) (*SearchOptionResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/search_option",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchOptionResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Option call failed: %w", err)
	}
	return result, nil
}

// SearchBoot executes the Boot RPC call of the Search controller
func (c *Controller) SearchBoot(ctx context.Context, rowCount string) (*SearchBootResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/search_boot",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchBootResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Boot call failed: %w", err)
	}
	return result, nil
}

// SearchTag executes the Tag RPC call of the Search controller
func (c *Controller) SearchTag(ctx context.Context, rowCount string) (*SearchTagResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/dnsmasq/settings/search_tag",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchTagResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Tag call failed: %w", err)
	}
	return result, nil
}
