// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var TagOpts = api.ReqOpts{
	AddEndpoint:         "/dnsmasq/settings/add_tag",
	GetEndpoint:         "/dnsmasq/settings/get_tag",
	UpdateEndpoint:      "/dnsmasq/settings/set_tag",
	DeleteEndpoint:      "/dnsmasq/settings/del_tag",
	ReconfigureEndpoint: dnsmasqReconfigureEndpoint,
	Monad:               "tag",
}

// Data structs

type Tag struct {
	Tag string `json:"tag"`
}

// CRUD operations

func (c *Controller) AddTag(ctx context.Context, resource *Tag) (string, error) {
	return api.Add(c.Client(), ctx, TagOpts, resource)
}

func (c *Controller) GetTag(ctx context.Context, id string) (*Tag, error) {
	return api.Get(c.Client(), ctx, TagOpts, &Tag{}, id)
}

func (c *Controller) UpdateTag(ctx context.Context, id string, resource *Tag) error {
	return api.Update(c.Client(), ctx, TagOpts, resource, id)
}

func (c *Controller) DeleteTag(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, TagOpts, id)
}
