// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package core

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type FirmwareActionResult struct {
	Status  string `json:"status"`
	MsgUUID string `json:"msg_uuid"`
}

type FirmwareInfo struct {
	ProductID      string            `json:"product_id"`
	ProductVersion string            `json:"product_version"`
	Packages       []FirmwarePackage `json:"package"`
	Plugins        []FirmwarePlugin  `json:"plugin"`
}

type FirmwarePackage struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	Comment    string `json:"comment"`
	Flatsize   string `json:"flatsize"`
	Locked     string `json:"locked"`
	Automatic  string `json:"automatic"`
	License    string `json:"license"`
	Repository string `json:"repository"`
	Origin     string `json:"origin"`
	Provided   string `json:"provided"`
	Installed  string `json:"installed"`
	Path       string `json:"path"`
	Configured string `json:"configured"`
}

type FirmwarePlugin struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	Comment    string `json:"comment"`
	Flatsize   string `json:"flatsize"`
	Locked     string `json:"locked"`
	Automatic  string `json:"automatic"`
	License    string `json:"license"`
	Repository string `json:"repository"`
	Origin     string `json:"origin"`
	Provided   string `json:"provided"`
	Installed  string `json:"installed"`
	Path       string `json:"path"`
	Configured string `json:"configured"`
	Tier       string `json:"tier"`
}

type FirmwareRunningStatus struct {
	Status string `json:"status"`
}

type FirmwareUpgradeStatus struct {
	Status string `json:"status"`
	Log    string `json:"log"`
}

// FirmwareInfo executes the Info RPC call of the Firmware controller
func (c *Controller) FirmwareInfo(ctx context.Context) (*FirmwareInfo, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/info",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareInfo{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Info call failed: %w", err)
	}
	return result, nil
}

// FirmwareRunning executes the Running RPC call of the Firmware controller
func (c *Controller) FirmwareRunning(ctx context.Context) (*FirmwareRunningStatus, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/running",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareRunningStatus{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Running call failed: %w", err)
	}
	return result, nil
}

// FirmwareUpgradeStatus executes the UpgradeStatus RPC call of the Firmware controller
func (c *Controller) FirmwareUpgradeStatus(ctx context.Context) (*FirmwareUpgradeStatus, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/upgradestatus",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareUpgradeStatus{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("UpgradeStatus call failed: %w", err)
	}
	return result, nil
}

// FirmwareInstall executes the Install RPC call of the Firmware controller
func (c *Controller) FirmwareInstall(ctx context.Context, pkgName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, pkgName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/install",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Install call failed: %w", err)
	}
	return result, nil
}

// FirmwareRemove executes the Remove RPC call of the Firmware controller
func (c *Controller) FirmwareRemove(ctx context.Context, pkgName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, pkgName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/remove",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Remove call failed: %w", err)
	}
	return result, nil
}

// FirmwareReinstall executes the Reinstall RPC call of the Firmware controller
func (c *Controller) FirmwareReinstall(ctx context.Context, pkgName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, pkgName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/reinstall",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reinstall call failed: %w", err)
	}
	return result, nil
}

// FirmwareLock executes the Lock RPC call of the Firmware controller
func (c *Controller) FirmwareLock(ctx context.Context, pkgName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, pkgName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/lock",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Lock call failed: %w", err)
	}
	return result, nil
}

// FirmwareUnlock executes the Unlock RPC call of the Firmware controller
func (c *Controller) FirmwareUnlock(ctx context.Context, pkgName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, pkgName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/unlock",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Unlock call failed: %w", err)
	}
	return result, nil
}
