// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package core

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type Action struct {
	Status      string `json:"status"`
	MessageUUID string `json:"msg_uuid"`
}

type Info struct {
	Plugin []Package `json:"plugin"`
}

type Package struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	Installed  string `json:"installed"`
	Provided   string `json:"provided"`
	Configured string `json:"configured"`
	Repository string `json:"repository"`
}

// FirmwareInfo executes the Info RPC call of the Firmware controller
func (c *Controller) FirmwareInfo(ctx context.Context) (*Info, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/info",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Info{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Info call failed: %w", err)
	}
	return result, nil
}

// FirmwareInstall executes the Install RPC call of the Firmware controller
func (c *Controller) FirmwareInstall(ctx context.Context, packageName string) (*Action, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/install",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Action{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Install call failed: %w", err)
	}
	return result, nil
}

// FirmwareRemove executes the Remove RPC call of the Firmware controller
func (c *Controller) FirmwareRemove(ctx context.Context, packageName string) (*Action, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/core/firmware/remove",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &Action{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Remove call failed: %w", err)
	}
	return result, nil
}
