// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package wireguard

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type GenKeyPairResult struct {
	PrivKey string `json:"privkey"`
	PubKey  string `json:"pubkey"`
	Status  string `json:"status"`
}

type GenPskResult struct {
	Psk    string `json:"psk"`
	Status string `json:"status"`
}

// ServiceGenKeyPair executes the GenKeyPair RPC call of the Service controller
func (c *Controller) ServiceGenKeyPair(ctx context.Context) (*GenKeyPairResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/wireguard/server/keyPair",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GenKeyPairResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GenKeyPair call failed: %w", err)
	}
	return result, nil
}

// ServiceGenPsk executes the GenPsk RPC call of the Service controller
func (c *Controller) ServiceGenPsk(ctx context.Context) (*GenPskResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/wireguard/client/psk",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GenPskResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GenPsk call failed: %w", err)
	}
	return result, nil
}
