// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trust

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var CaOpts = api.ReqOpts{
	AddEndpoint:         "/trust/ca/add",
	GetEndpoint:         "/trust/ca/get",
	UpdateEndpoint:      "/trust/ca/set",
	DeleteEndpoint:      "/trust/ca/del",
	ReconfigureEndpoint: "",
	Monad:               "ca",
}

// Data structs

type Ca struct {
	RefId              string          `json:"refid,omitempty"`
	Description        string          `json:"descr"`
	Action             api.SelectedMap `json:"action"`
	Crt                string          `json:"crt"`
	Prv                string          `json:"prv"`
	Serial             string          `json:"serial,omitempty"`
	CaRef              api.SelectedMap `json:"caref"`
	KeyType            api.SelectedMap `json:"key_type"`
	Lifetime           string          `json:"lifetime"`
	Digest             api.SelectedMap `json:"digest"`
	Country            api.SelectedMap `json:"country"`
	State              string          `json:"state"`
	City               string          `json:"city"`
	Organization       string          `json:"organization"`
	OrganizationalUnit string          `json:"organizationalunit"`
	Email              string          `json:"email"`
	CommonName         string          `json:"commonname"`
	OcspUri            string          `json:"ocsp_uri"`
	CrtPayload         string          `json:"crt_payload,omitempty"`
	PrvPayload         string          `json:"prv_payload,omitempty"`
	Refcount           string          `json:"refcount,omitempty"`
	Name               string          `json:"name,omitempty"`
	ValidFrom          string          `json:"valid_from,omitempty"`
	ValidTo            string          `json:"valid_to,omitempty"`
}

// CRUD operations

func (c *Controller) AddCa(ctx context.Context, resource *Ca) (string, error) {
	return api.Add(c.Client(), ctx, CaOpts, resource)
}

func (c *Controller) GetCa(ctx context.Context, id string) (*Ca, error) {
	return api.Get(c.Client(), ctx, CaOpts, &Ca{}, id)
}

func (c *Controller) UpdateCa(ctx context.Context, id string, resource *Ca) error {
	return api.Update(c.Client(), ctx, CaOpts, resource, id)
}

func (c *Controller) DeleteCa(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, CaOpts, id)
}
