// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trust

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var CertOpts = api.ReqOpts{
	AddEndpoint:         "/trust/cert/add",
	GetEndpoint:         "/trust/cert/get",
	UpdateEndpoint:      "/trust/cert/set",
	DeleteEndpoint:      "/trust/cert/del",
	ReconfigureEndpoint: "",
	Monad:               "cert",
}

// Data structs

type Cert struct {
	RefId              string          `json:"refid,omitempty"`
	Description        string          `json:"descr"`
	CaRef              api.SelectedMap `json:"caref"`
	Crt                string          `json:"crt"`
	Csr                string          `json:"csr"`
	Prv                string          `json:"prv"`
	Action             api.SelectedMap `json:"action"`
	KeyType            api.SelectedMap `json:"key_type"`
	Digest             api.SelectedMap `json:"digest"`
	CertType           api.SelectedMap `json:"cert_type"`
	Lifetime           string          `json:"lifetime"`
	PrivateKeyLocation api.SelectedMap `json:"private_key_location"`
	Country            api.SelectedMap `json:"country"`
	State              string          `json:"state"`
	City               string          `json:"city"`
	Organization       string          `json:"organization"`
	OrganizationalUnit string          `json:"organizationalunit"`
	Email              string          `json:"email"`
	CommonName         string          `json:"commonname"`
	OcspUri            string          `json:"ocsp_uri"`
	AltnamesDns        string          `json:"altnames_dns"`
	AltnamesIp         string          `json:"altnames_ip"`
	AltnamesUri        string          `json:"altnames_uri"`
	AltnamesEmail      string          `json:"altnames_email"`
	Rfc3280Purpose     string          `json:"rfc3280_purpose"`
	InUse              string          `json:"in_use,omitempty"`
	IsUser             string          `json:"is_user,omitempty"`
	CrtPayload         string          `json:"crt_payload,omitempty"`
	CsrPayload         string          `json:"csr_payload,omitempty"`
	PrvPayload         string          `json:"prv_payload,omitempty"`
	Name               string          `json:"name,omitempty"`
	ValidFrom          string          `json:"valid_from,omitempty"`
	ValidTo            string          `json:"valid_to,omitempty"`
}

// CRUD operations

func (c *Controller) AddCert(ctx context.Context, resource *Cert) (string, error) {
	return api.Add(c.Client(), ctx, CertOpts, resource)
}

func (c *Controller) GetCert(ctx context.Context, id string) (*Cert, error) {
	return api.Get(c.Client(), ctx, CertOpts, &Cert{}, id)
}

func (c *Controller) UpdateCert(ctx context.Context, id string, resource *Cert) error {
	return api.Update(c.Client(), ctx, CertOpts, resource, id)
}

func (c *Controller) DeleteCert(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, CertOpts, id)
}
