// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trust

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type ActionResult struct {
	Status string `json:"status"`
}

type TrustSettings struct {
	StoreIntermediateCerts  string              `json:"store_intermediate_certs"`
	InstallCrls             string              `json:"install_crls"`
	FetchCrls               string              `json:"fetch_crls"`
	EnableLegacySect        string              `json:"enable_legacy_sect"`
	EnableConfigConstraints string              `json:"enable_config_constraints"`
	CipherString            api.SelectedMapList `json:"CipherString"`
}

type TrustSettingsMonad struct {
	Trust TrustSettings `json:"trust"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*TrustSettingsMonad, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/trust/settings/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &TrustSettingsMonad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, trust *TrustSettings) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["trust"] = trust

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/trust/settings/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Set call failed: %w", err)
	}
	return result, nil
}

// SettingsReconfigure executes the Reconfigure RPC call of the Settings controller
func (c *Controller) SettingsReconfigure(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/trust/settings/reconfigure",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reconfigure call failed: %w", err)
	}
	return result, nil
}
