// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var KeaReservationOpts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv4/add_reservation",
	GetEndpoint:         "/kea/dhcpv4/get_reservation",
	UpdateEndpoint:      "/kea/dhcpv4/set_reservation",
	DeleteEndpoint:      "/kea/dhcpv4/del_reservation",
	SearchEndpoint:      "/kea/dhcpv4/search_reservation",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "reservation",
}

// Data structs

type KeaReservation struct {
	Subnet      api.SelectedMapList `json:"subnet"`
	IpAddress   string              `json:"ip_address"`
	HwAddress   string              `json:"hw_address"`
	Hostname    string              `json:"hostname"`
	Description string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddKeaReservation(ctx context.Context, resource *KeaReservation) (string, error) {
	return api.Add(c.Client(), ctx, KeaReservationOpts, resource)
}

func (c *Controller) GetKeaReservation(ctx context.Context, id string) (*KeaReservation, error) {
	return api.Get(c.Client(), ctx, KeaReservationOpts, &KeaReservation{}, id)
}

func (c *Controller) UpdateKeaReservation(ctx context.Context, id string, resource *KeaReservation) error {
	return api.Update(c.Client(), ctx, KeaReservationOpts, resource, id)
}

func (c *Controller) DeleteKeaReservation(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, KeaReservationOpts, id)
}

func (c *Controller) SearchKeaReservation(ctx context.Context, filter string) ([]KeaReservation, error) {
	return api.Search(c.Client(), ctx, KeaReservationOpts, []KeaReservation{}, filter)
}
