// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var PDPoolOpts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv6/add_pd_pool",
	GetEndpoint:         "/kea/dhcpv6/get_pd_pool",
	UpdateEndpoint:      "/kea/dhcpv6/set_pd_pool",
	DeleteEndpoint:      "/kea/dhcpv6/del_pd_pool",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "pd_pool",
}

// Data structs

type PDPool struct {
	Subnet       api.SelectedMap `json:"subnet"`
	Prefix       string          `json:"prefix"`
	PrefixLen    string          `json:"prefix_len"`
	DelegatedLen string          `json:"delegated_len"`
	Description  string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddPDPool(ctx context.Context, resource *PDPool) (string, error) {
	return api.Add(c.Client(), ctx, PDPoolOpts, resource)
}

func (c *Controller) GetPDPool(ctx context.Context, id string) (*PDPool, error) {
	return api.Get(c.Client(), ctx, PDPoolOpts, &PDPool{}, id)
}

func (c *Controller) UpdatePDPool(ctx context.Context, id string, resource *PDPool) error {
	return api.Update(c.Client(), ctx, PDPoolOpts, resource, id)
}

func (c *Controller) DeletePDPool(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PDPoolOpts, id)
}
