// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var PeerOpts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv4/add_peer",
	GetEndpoint:         "/kea/dhcpv4/get_peer",
	UpdateEndpoint:      "/kea/dhcpv4/set_peer",
	DeleteEndpoint:      "/kea/dhcpv4/del_peer",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "peer",
}

// Data structs

type Peer struct {
	Name string          `json:"name"`
	Url  string          `json:"url"`
	Role api.SelectedMap `json:"role"`
}

// CRUD operations

func (c *Controller) AddPeer(ctx context.Context, resource *Peer) (string, error) {
	return api.Add(c.Client(), ctx, PeerOpts, resource)
}

func (c *Controller) GetPeer(ctx context.Context, id string) (*Peer, error) {
	return api.Get(c.Client(), ctx, PeerOpts, &Peer{}, id)
}

func (c *Controller) UpdatePeer(ctx context.Context, id string, resource *Peer) error {
	return api.Update(c.Client(), ctx, PeerOpts, resource, id)
}

func (c *Controller) DeletePeer(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PeerOpts, id)
}
