// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var PeerV4Opts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv4/add_peer",
	GetEndpoint:         "/kea/dhcpv4/get_peer",
	UpdateEndpoint:      "/kea/dhcpv4/set_peer",
	DeleteEndpoint:      "/kea/dhcpv4/del_peer",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "peer",
}

// Data structs

type PeerV4 struct {
	Name string          `json:"name"`
	Url  string          `json:"url"`
	Role api.SelectedMap `json:"role"`
}

// CRUD operations

func (c *Controller) AddPeerV4(ctx context.Context, resource *PeerV4) (string, error) {
	return api.Add(c.Client(), ctx, PeerV4Opts, resource)
}

func (c *Controller) GetPeerV4(ctx context.Context, id string) (*PeerV4, error) {
	return api.Get(c.Client(), ctx, PeerV4Opts, &PeerV4{}, id)
}

func (c *Controller) UpdatePeerV4(ctx context.Context, id string, resource *PeerV4) error {
	return api.Update(c.Client(), ctx, PeerV4Opts, resource, id)
}

func (c *Controller) DeletePeerV4(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PeerV4Opts, id)
}
