// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var PeerV6Opts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv6/add_peer",
	GetEndpoint:         "/kea/dhcpv6/get_peer",
	UpdateEndpoint:      "/kea/dhcpv6/set_peer",
	DeleteEndpoint:      "/kea/dhcpv6/del_peer",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "peer",
}

// Data structs

type PeerV6 struct {
	Name string          `json:"name"`
	Url  string          `json:"url"`
	Role api.SelectedMap `json:"role"`
}

// CRUD operations

func (c *Controller) AddPeerV6(ctx context.Context, resource *PeerV6) (string, error) {
	return api.Add(c.Client(), ctx, PeerV6Opts, resource)
}

func (c *Controller) GetPeerV6(ctx context.Context, id string) (*PeerV6, error) {
	return api.Get(c.Client(), ctx, PeerV6Opts, &PeerV6{}, id)
}

func (c *Controller) UpdatePeerV6(ctx context.Context, id string, resource *PeerV6) error {
	return api.Update(c.Client(), ctx, PeerV6Opts, resource, id)
}

func (c *Controller) DeletePeerV6(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PeerV6Opts, id)
}
