// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var ReservationV6Opts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv6/add_reservation",
	GetEndpoint:         "/kea/dhcpv6/get_reservation",
	UpdateEndpoint:      "/kea/dhcpv6/set_reservation",
	DeleteEndpoint:      "/kea/dhcpv6/del_reservation",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "reservation",
}

// Data structs

type ReservationV6 struct {
	Subnet       api.SelectedMap     `json:"subnet"`
	IpAddress    string              `json:"ip_address"`
	DUID         string              `json:"duid"`
	Hostname     string              `json:"hostname"`
	DomainSearch api.SelectedMapList `json:"domain_search"`
	Description  string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddReservationV6(ctx context.Context, resource *ReservationV6) (string, error) {
	return api.Add(c.Client(), ctx, ReservationV6Opts, resource)
}

func (c *Controller) GetReservationV6(ctx context.Context, id string) (*ReservationV6, error) {
	return api.Get(c.Client(), ctx, ReservationV6Opts, &ReservationV6{}, id)
}

func (c *Controller) UpdateReservationV6(ctx context.Context, id string, resource *ReservationV6) error {
	return api.Update(c.Client(), ctx, ReservationV6Opts, resource, id)
}

func (c *Controller) DeleteReservationV6(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ReservationV6Opts, id)
}
