// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var ReservationV4Opts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv4/add_reservation",
	GetEndpoint:         "/kea/dhcpv4/get_reservation",
	UpdateEndpoint:      "/kea/dhcpv4/set_reservation",
	DeleteEndpoint:      "/kea/dhcpv4/del_reservation",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "reservation",
}

// Data structs

type ReservationV4 struct {
	Subnet      api.SelectedMap `json:"subnet"`
	IpAddress   string          `json:"ip_address"`
	HwAddress   string          `json:"hw_address"`
	Hostname    string          `json:"hostname"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddReservationV4(ctx context.Context, resource *ReservationV4) (string, error) {
	return api.Add(c.Client(), ctx, ReservationV4Opts, resource)
}

func (c *Controller) GetReservationV4(ctx context.Context, id string) (*ReservationV4, error) {
	return api.Get(c.Client(), ctx, ReservationV4Opts, &ReservationV4{}, id)
}

func (c *Controller) UpdateReservationV4(ctx context.Context, id string, resource *ReservationV4) error {
	return api.Update(c.Client(), ctx, ReservationV4Opts, resource, id)
}

func (c *Controller) DeleteReservationV4(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ReservationV4Opts, id)
}
