// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"fmt"

	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type ActionResult struct {
	Status string `json:"status"`
}

type DHCPv4General struct {
	Enabled        string              `json:"enabled"`
	ManualConfig   string              `json:"manual_config"`
	Interfaces     api.SelectedMapList `json:"interfaces"`
	ValidLifetime  string              `json:"valid_lifetime"`
	FWRules        string              `json:"fwrules"`
	DHCPSocketType api.SelectedMap     `json:"dhcp_socket_type"`
}

type DHCPv4Monad struct {
	DHCPv4 DHCPv4Settings `json:"dhcpv4"`
}

type DHCPv4Settings struct {
	General      DHCPv4General `json:"general"`
	LeaseExpire  LeaseExpire   `json:"lexpire"`
	HA           HA            `json:"ha"`
	ThisHostname string        `json:"this_hostname"`
}

type DHCPv6General struct {
	Enabled       string              `json:"enabled"`
	ManualConfig  string              `json:"manual_config"`
	Interfaces    api.SelectedMapList `json:"interfaces"`
	ValidLifetime string              `json:"valid_lifetime"`
	FWRules       string              `json:"fwrules"`
}

type DHCPv6Monad struct {
	DHCPv6 DHCPv6Settings `json:"dhcpv6"`
}

type DHCPv6Settings struct {
	General      DHCPv6General `json:"general"`
	LeaseExpire  LeaseExpire   `json:"lexpire"`
	HA           HA            `json:"ha"`
	ThisHostname string        `json:"this_hostname"`
}

type HA struct {
	Enabled           string `json:"enabled"`
	ThisServerName    string `json:"this_server_name"`
	MaxUnackedClients string `json:"max_unacked_clients"`
}

type LeaseExpire struct {
	HoldReclaimedTime           string `json:"hold_reclaimed_time"`
	ReclaimTimerWaitTime        string `json:"reclaim_timer_wait_time"`
	FlushReclaimedTimerWaitTime string `json:"flush_reclaimed_timer_wait_time"`
	MaxReclaimTime              string `json:"max_reclaim_time"`
	MaxReclaimLeases            string `json:"max_reclaim_leases"`
	UnwarnedReclaimCycles       string `json:"unwarned_reclaim_cycles"`
}

type Result struct {
	Result string `json:"result"`
}

// SettingsDHCPv4Get executes the DHCPv4Get RPC call of the Settings controller
func (c *Controller) SettingsDHCPv4Get(ctx context.Context) (*DHCPv4Monad, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/kea/dhcpv4/get",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &DHCPv4Monad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("DHCPv4Get call failed: %w", err)
	}
	return result, nil
}

// SettingsDHCPv4Update executes the DHCPv4Update RPC call of the Settings controller
func (c *Controller) SettingsDHCPv4Update(ctx context.Context, dhcpv4 *DHCPv4Settings) (*Result, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["dhcpv4"] = dhcpv4

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/kea/dhcpv4/set",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("DHCPv4Update call failed: %w", err)
	}
	return result, nil
}

// SettingsDHCPv6Get executes the DHCPv6Get RPC call of the Settings controller
func (c *Controller) SettingsDHCPv6Get(ctx context.Context) (*DHCPv6Monad, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/kea/dhcpv6/get",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &DHCPv6Monad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("DHCPv6Get call failed: %w", err)
	}
	return result, nil
}

// SettingsDHCPv6Update executes the DHCPv6Update RPC call of the Settings controller
func (c *Controller) SettingsDHCPv6Update(ctx context.Context, dhcpv6 *DHCPv6Settings) (*Result, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["dhcpv6"] = dhcpv6

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/kea/dhcpv6/set",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("DHCPv6Update call failed: %w", err)
	}
	return result, nil
}

// SettingsReconfigure executes the Reconfigure RPC call of the Settings controller
func (c *Controller) SettingsReconfigure(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/kea/service/reconfigure",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reconfigure call failed: %w", err)
	}
	return result, nil
}
