// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var SubnetV4Opts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv4/add_subnet",
	GetEndpoint:         "/kea/dhcpv4/get_subnet",
	UpdateEndpoint:      "/kea/dhcpv4/set_subnet",
	DeleteEndpoint:      "/kea/dhcpv4/del_subnet",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "subnet4",
}

// Data structs

type OptionDataV4 struct {
	DomainNameServers api.SelectedMapList `json:"domain_name_servers"`
	DomainSearch      api.SelectedMapList `json:"domain_search"`
	Routers           api.SelectedMapList `json:"routers"`
	StaticRoutes      string              `json:"static_routes"`
	DomainName        string              `json:"domain_name"`
	NtpServers        api.SelectedMapList `json:"ntp_servers"`
	TimeServers       api.SelectedMapList `json:"time_servers"`
	TftpServerName    string              `json:"tftp_server_name"`
	BootFileName      string              `json:"boot_file_name"`
}

type SubnetV4 struct {
	Subnet                string       `json:"subnet"`
	NextServer            string       `json:"next_server"`
	Pools                 string       `json:"pools"`
	MatchClientId         string       `json:"match-client-id"`
	OptionDataAutoCollect string       `json:"option_data_autocollect"`
	OptionData            OptionDataV4 `json:"option_data"`
	Description           string       `json:"description"`
}

// CRUD operations

func (c *Controller) AddSubnetV4(ctx context.Context, resource *SubnetV4) (string, error) {
	return api.Add(c.Client(), ctx, SubnetV4Opts, resource)
}

func (c *Controller) GetSubnetV4(ctx context.Context, id string) (*SubnetV4, error) {
	return api.Get(c.Client(), ctx, SubnetV4Opts, &SubnetV4{}, id)
}

func (c *Controller) UpdateSubnetV4(ctx context.Context, id string, resource *SubnetV4) error {
	return api.Update(c.Client(), ctx, SubnetV4Opts, resource, id)
}

func (c *Controller) DeleteSubnetV4(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, SubnetV4Opts, id)
}
