// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package kea

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var SubnetV6Opts = api.ReqOpts{
	AddEndpoint:         "/kea/dhcpv6/add_subnet",
	GetEndpoint:         "/kea/dhcpv6/get_subnet",
	UpdateEndpoint:      "/kea/dhcpv6/set_subnet",
	DeleteEndpoint:      "/kea/dhcpv6/del_subnet",
	ReconfigureEndpoint: keaReconfigureEndpoint,
	Monad:               "subnet6",
}

// Data structs

type OptionDataV6 struct {
	DomainNameServers api.SelectedMapList `json:"dns_servers"`
	DomainSearch      api.SelectedMapList `json:"domain_search"`
}

type SubnetV6 struct {
	Subnet      string          `json:"subnet"`
	Allocator   api.SelectedMap `json:"allocator"`
	PDAllocator api.SelectedMap `json:"pd-allocator"`
	Pools       string          `json:"pools"`
	Interface   api.SelectedMap `json:"interface"`
	OptionData  OptionDataV6    `json:"option_data"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddSubnetV6(ctx context.Context, resource *SubnetV6) (string, error) {
	return api.Add(c.Client(), ctx, SubnetV6Opts, resource)
}

func (c *Controller) GetSubnetV6(ctx context.Context, id string) (*SubnetV6, error) {
	return api.Get(c.Client(), ctx, SubnetV6Opts, &SubnetV6{}, id)
}

func (c *Controller) UpdateSubnetV6(ctx context.Context, id string, resource *SubnetV6) error {
	return api.Update(c.Client(), ctx, SubnetV6Opts, resource, id)
}

func (c *Controller) DeleteSubnetV6(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, SubnetV6Opts, id)
}
