// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package unbound

import "github.com/browningluke/opnsense-go/pkg/api"

const unboundReconfigureEndpoint = "/unbound/service/reconfigure"

// Controller for unbound
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
