// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package unbound

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var DotOpts = api.ReqOpts{
	AddEndpoint:         "/unbound/settings/addDot",
	GetEndpoint:         "/unbound/settings/getDot",
	UpdateEndpoint:      "/unbound/settings/setDot",
	DeleteEndpoint:      "/unbound/settings/delDot",
	ReconfigureEndpoint: unboundReconfigureEndpoint,
	Monad:               "dot",
}

// Data structs

type Dot struct {
	Enabled  string          `json:"enabled"`
	Domain   string          `json:"domain"`
	Type     api.SelectedMap `json:"type"`
	Server   string          `json:"server"`
	Port     string          `json:"port"`
	VerifyCN string          `json:"verify"`
}

// CRUD operations

func (c *Controller) AddDot(ctx context.Context, resource *Dot) (string, error) {
	return api.Add(c.Client(), ctx, DotOpts, resource)
}

func (c *Controller) GetDot(ctx context.Context, id string) (*Dot, error) {
	return api.Get(c.Client(), ctx, DotOpts, &Dot{}, id)
}

func (c *Controller) UpdateDot(ctx context.Context, id string, resource *Dot) error {
	return api.Update(c.Client(), ctx, DotOpts, resource, id)
}

func (c *Controller) DeleteDot(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, DotOpts, id)
}
