// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package unbound

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type SearchForwardItem struct {
	Id       string          `json:"uuid"`
	Enabled  string          `json:"enabled"`
	Domain   string          `json:"domain"`
	Type     api.SelectedMap `json:"type"`
	Server   string          `json:"server"`
	Port     string          `json:"port"`
	VerifyCN string          `json:"verify"`
}

type SearchForwardResponse struct {
	Current  int                 `json:"current"`
	RowCount int                 `json:"rowCount"`
	Total    int                 `json:"total"`
	Rows     []SearchForwardItem `json:"rows"`
}

type SearchHostAliasItem struct {
	Id          string          `json:"uuid"`
	Enabled     string          `json:"enabled"`
	Host        api.SelectedMap `json:"host"`
	Hostname    string          `json:"hostname"`
	Domain      string          `json:"domain"`
	Description string          `json:"description"`
}

type SearchHostAliasResponse struct {
	Current  int                   `json:"current"`
	RowCount int                   `json:"rowCount"`
	Total    int                   `json:"total"`
	Rows     []SearchHostAliasItem `json:"rows"`
}

type SearchHostOverrideItem struct {
	Id          string `json:"uuid"`
	Enabled     string `json:"enabled"`
	Hostname    string `json:"hostname"`
	Domain      string `json:"domain"`
	Type        string `json:"rr"`
	Server      string `json:"server"`
	MXPriority  string `json:"mxprio"`
	MXDomain    string `json:"mx"`
	Description string `json:"description"`
}

type SearchHostOverrideResponse struct {
	Current  int                      `json:"current"`
	RowCount int                      `json:"rowCount"`
	Total    int                      `json:"total"`
	Rows     []SearchHostOverrideItem `json:"rows"`
}

// SearchHostOverride executes the HostOverride RPC call of the Search controller
func (c *Controller) SearchHostOverride(ctx context.Context, rowCount string) (*SearchHostOverrideResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/settings/search_host_override",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchHostOverrideResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("HostOverride call failed: %w", err)
	}
	return result, nil
}

// SearchHostAlias executes the HostAlias RPC call of the Search controller
func (c *Controller) SearchHostAlias(ctx context.Context, rowCount string) (*SearchHostAliasResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/settings/search_host_alias",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchHostAliasResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("HostAlias call failed: %w", err)
	}
	return result, nil
}

// SearchForward executes the Forward RPC call of the Search controller
func (c *Controller) SearchForward(ctx context.Context, rowCount string) (*SearchForwardResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/settings/search_forward",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchForwardResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Forward call failed: %w", err)
	}
	return result, nil
}
