// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package unbound

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type ACLs struct {
	DefaultAction api.SelectedMap `json:"default_action"`
}

type ActionResult struct {
	Status string `json:"status"`
}

type Advanced struct {
	HideIdentity              string              `json:"hideidentity"`
	HideVersion               string              `json:"hideversion"`
	Prefetch                  string              `json:"prefetch"`
	PrefetchKey               string              `json:"prefetchkey"`
	DNSSECStripped            string              `json:"dnssecstripped"`
	AggressiveNSEC            string              `json:"aggressivensec"`
	ServeExpired              string              `json:"serveexpired"`
	ServeExpiredReplyTTL      string              `json:"serveexpiredreplyttl"`
	ServeExpiredTTL           string              `json:"serveexpiredttl"`
	ServeExpiredTTLReset      string              `json:"serveexpiredttlreset"`
	ServeExpiredClientTimeout string              `json:"serveexpiredclienttimeout"`
	QnameMinStrict            string              `json:"qnameminstrict"`
	ExtendedStatistics        string              `json:"extendedstatistics"`
	LogQueries                string              `json:"logqueries"`
	LogReplies                string              `json:"logreplies"`
	LogTagQueryReply          string              `json:"logtagqueryreply"`
	LogServFail               string              `json:"logservfail"`
	LogLocalActions           string              `json:"loglocalactions"`
	LogVerbosity              api.SelectedMap     `json:"logverbosity"`
	ValLogLevel               api.SelectedMap     `json:"valloglevel"`
	PrivateDomain             api.SelectedMapList `json:"privatedomain"`
	PrivateAddress            api.SelectedMapList `json:"privateaddress"`
	InsecureDomain            api.SelectedMapList `json:"insecuredomain"`
	MsgCacheSize              string              `json:"msgcachesize"`
	RRSetCacheSize            string              `json:"rrsetcachesize"`
	OutgoingNumTCP            string              `json:"outgoingnumtcp"`
	IncomingNumTCP            string              `json:"incomingnumtcp"`
	NumQueriesPerThread       string              `json:"numqueriesperthread"`
	OutgoingRange             string              `json:"outgoingrange"`
	JostleTimeout             string              `json:"jostletimeout"`
	DiscardTimeout            string              `json:"discardtimeout"`
	CacheMaxTTL               string              `json:"cachemaxttl"`
	CacheMaxNegativeTTL       string              `json:"cachemaxnegativettl"`
	CacheMinTTL               string              `json:"cacheminttl"`
	InfraHostTTL              string              `json:"infrahostttl"`
	InfraKeepProbing          string              `json:"infrakeepprobing"`
	InfraCacheNumHosts        string              `json:"infracachenumhosts"`
	UnwantedReplyThreshold    string              `json:"unwantedreplythreshold"`
}

type DNSBL struct {
	Enabled    string              `json:"enabled"`
	SafeSearch string              `json:"safesearch"`
	Type       api.SelectedMapList `json:"type"`
	Lists      api.SelectedMapList `json:"lists"`
	Whitelists api.SelectedMapList `json:"whitelists"`
	Blocklists api.SelectedMapList `json:"blocklists"`
	Wildcards  api.SelectedMapList `json:"wildcards"`
	Address    string              `json:"address"`
	NXDomain   string              `json:"nxdomain"`
}

type Forwarding struct {
	Enabled string `json:"enabled"`
}

type General struct {
	Enabled           string              `json:"enabled"`
	Port              string              `json:"port"`
	Stats             string              `json:"stats"`
	ActiveInterface   api.SelectedMapList `json:"active_interface"`
	DNSSEC            string              `json:"dnssec"`
	DNS64             string              `json:"dns64"`
	DNS64Prefix       string              `json:"dns64prefix"`
	NoARecords        string              `json:"noarecords"`
	RegDHCP           string              `json:"regdhcp"`
	RegDHCPDomain     string              `json:"regdhcpdomain"`
	RegDHCPStatic     string              `json:"regdhcpstatic"`
	NoRegLLAddr6      string              `json:"noreglladdr6"`
	NoRegRecords      string              `json:"noregrecords"`
	TXTSupport        string              `json:"txtsupport"`
	CacheFlush        string              `json:"cacheflush"`
	LocalZoneType     api.SelectedMap     `json:"local_zone_type"`
	OutgoingInterface api.SelectedMapList `json:"outgoing_interface"`
	EnableWPAD        string              `json:"enable_wpad"`
}

type Result struct {
	Result string `json:"result"`
}

type Settings struct {
	General    General    `json:"general"`
	Advanced   Advanced   `json:"advanced"`
	ACLs       ACLs       `json:"acls"`
	DNSBL      DNSBL      `json:"dnsbl"`
	Forwarding Forwarding `json:"forwarding"`
}

type SettingsMonad struct {
	Unbound Settings `json:"unbound"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsMonad, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/settings/get",
		Method:         "GET",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SettingsMonad{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Get call failed: %w", err)
	}
	return result, nil
}

// SettingsUpdate executes the Update RPC call of the Settings controller
func (c *Controller) SettingsUpdate(ctx context.Context, unbound *Settings) (*Result, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["unbound"] = unbound

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/settings/set",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &Result{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Update call failed: %w", err)
	}
	return result, nil
}

// SettingsReconfigure executes the Reconfigure RPC call of the Settings controller
func (c *Controller) SettingsReconfigure(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/service/reconfigure",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("Reconfigure call failed: %w", err)
	}
	return result, nil
}

// SettingsReconfigureGeneral executes the ReconfigureGeneral RPC call of the Settings controller
func (c *Controller) SettingsReconfigureGeneral(ctx context.Context) (*ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/unbound/service/reconfigure_general",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("ReconfigureGeneral call failed: %w", err)
	}
	return result, nil
}
